// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors

package indexer

import (
	"strings"
	"testing"
)

func TestDetectAIGenerated_Empty(t *testing.T) {
	result := DetectAIGenerated("", "go", nil)
	if result.Score != 0 {
		t.Errorf("expected score 0 for empty content, got %f", result.Score)
	}
	if len(result.Signals) != 0 {
		t.Errorf("expected no signals, got %v", result.Signals)
	}
}

func TestDetectAIGenerated_ShortFile(t *testing.T) {
	content := "package main\n\nfunc main() {}\n"
	result := DetectAIGenerated(content, "go", nil)
	if result.Score != 0 {
		t.Errorf("expected score 0 for short file (<10 lines), got %f", result.Score)
	}
}

func TestDetectAIGenerated_AIAttribution(t *testing.T) {
	lines := make([]string, 15)
	lines[0] = "// Generated by ChatGPT"
	for i := 1; i < 15; i++ {
		lines[i] = "x := i"
	}
	content := strings.Join(lines, "\n")
	result := DetectAIGenerated(content, "go", nil)

	if result.Score < 0.30 {
		t.Errorf("expected score >= 0.30 for AI attribution, got %f", result.Score)
	}
	found := false
	for _, s := range result.Signals {
		if s == "ai_attribution" {
			found = true
		}
	}
	if !found {
		t.Error("expected ai_attribution signal")
	}
}

func TestDetectAIGenerated_GenericComments(t *testing.T) {
	var lines []string
	for i := 0; i < 20; i++ {
		lines = append(lines, "// Loop through the items")
		lines = append(lines, "for i := range items {}")
	}
	content := strings.Join(lines, "\n")
	result := DetectAIGenerated(content, "go", nil)

	found := false
	for _, s := range result.Signals {
		if s == "generic_comments" {
			found = true
		}
	}
	if !found {
		t.Error("expected generic_comments signal")
	}
}

func TestDetectAIGenerated_NoTodoInLargeFile(t *testing.T) {
	var lines []string
	for i := 0; i < 60; i++ {
		lines = append(lines, "x := i")
	}
	content := strings.Join(lines, "\n")
	result := DetectAIGenerated(content, "go", nil)

	found := false
	for _, s := range result.Signals {
		if s == "no_todo_or_hack" {
			found = true
		}
	}
	if !found {
		t.Error("expected no_todo_or_hack signal for large file without TODOs")
	}
}

func TestDetectAIGenerated_WithTodo(t *testing.T) {
	var lines []string
	for i := 0; i < 60; i++ {
		lines = append(lines, "x := i")
	}
	lines[30] = "// TODO: fix this"
	content := strings.Join(lines, "\n")
	result := DetectAIGenerated(content, "go", nil)

	for _, s := range result.Signals {
		if s == "no_todo_or_hack" {
			t.Error("should not fire no_todo_or_hack when TODO is present")
		}
	}
}

func TestDetectAIGenerated_SuspiciouslyCompleteDocs(t *testing.T) {
	symbols := make([]Symbol, 6)
	for i := range symbols {
		symbols[i] = Symbol{
			Kind:       SymbolFunction,
			Name:       "Func" + string(rune('A'+i)),
			DocComment: "This function does something.",
		}
	}
	var lines []string
	for i := 0; i < 15; i++ {
		lines = append(lines, "x := i")
	}
	content := strings.Join(lines, "\n")
	result := DetectAIGenerated(content, "go", symbols)

	found := false
	for _, s := range result.Signals {
		if s == "suspiciously_complete_docs" {
			found = true
		}
	}
	if !found {
		t.Error("expected suspiciously_complete_docs signal")
	}
}

func TestDetectAIGenerated_ScoreClampedToOne(t *testing.T) {
	// Construct content that triggers many signals
	var lines []string
	lines = append(lines, "// Generated by GitHub Copilot")
	for i := 0; i < 60; i++ {
		lines = append(lines, "// Loop through the items")
		lines = append(lines, "this.x = x;")
		lines = append(lines, "func handler() {")
		lines = append(lines, "if err != nil {")
		lines = append(lines, "}")
	}
	content := strings.Join(lines, "\n")

	symbols := make([]Symbol, 8)
	for i := range symbols {
		symbols[i] = Symbol{
			Kind:       SymbolFunction,
			Name:       "handleRequest",
			DocComment: "Handles the request.",
		}
	}

	result := DetectAIGenerated(content, "go", symbols)
	if result.Score > 1.0 {
		t.Errorf("score should be clamped to 1.0, got %f", result.Score)
	}
}

func TestDetectAIGenerated_TemplateFunctionNames(t *testing.T) {
	symbols := make([]Symbol, 6)
	names := []string{"handleRequest", "processData", "validateInput", "createUser", "updateRecord", "deleteItem"}
	for i := range symbols {
		symbols[i] = Symbol{
			Kind: SymbolFunction,
			Name: names[i],
		}
	}
	var lines []string
	for i := 0; i < 15; i++ {
		lines = append(lines, "x := i")
	}
	content := strings.Join(lines, "\n")
	result := DetectAIGenerated(content, "go", symbols)

	found := false
	for _, s := range result.Signals {
		if s == "template_function_names" {
			found = true
		}
	}
	if !found {
		t.Error("expected template_function_names signal")
	}
}
