package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	commonv1 "github.com/sourcebridge/sourcebridge/gen/go/common/v1"
	knowledgev1 "github.com/sourcebridge/sourcebridge/gen/go/knowledge/v1"
	linkingv1 "github.com/sourcebridge/sourcebridge/gen/go/linking/v1"
	reasoningv1 "github.com/sourcebridge/sourcebridge/gen/go/reasoning/v1"
	requirementsv1 "github.com/sourcebridge/sourcebridge/gen/go/requirements/v1"
	"github.com/sourcebridge/sourcebridge/internal/events"
	"github.com/sourcebridge/sourcebridge/internal/git"
	graphstore "github.com/sourcebridge/sourcebridge/internal/graph"
	"github.com/sourcebridge/sourcebridge/internal/indexer"
	knowledgepkg "github.com/sourcebridge/sourcebridge/internal/knowledge"
	"github.com/sourcebridge/sourcebridge/internal/requirements"
	"github.com/sourcebridge/sourcebridge/internal/version"
)

// AddRepository is the resolver for the addRepository field.
func (r *mutationResolver) AddRepository(ctx context.Context, input AddRepositoryInput) (*Repository, error) {
	store := r.getStore(ctx)
	if store == nil {
		return nil, fmt.Errorf("store not initialized")
	}

	repoPath := input.Path
	isRemote := isGitURL(repoPath)

	// Dedup check: return existing repo if already tracked
	if isRemote {
		normalizedURL := normalizeGitURL(repoPath)
		for _, existing := range store.ListRepositories() {
			if existing.RemoteURL == normalizedURL {
				return mapRepository(existing), nil
			}
		}
	} else {
		absPath, err := filepath.Abs(repoPath)
		if err != nil {
			return nil, fmt.Errorf("resolving path: %w", err)
		}
		if existing := store.GetRepositoryByPath(absPath); existing != nil {
			return mapRepository(existing), nil
		}
	}

	// Create a placeholder repo with PENDING status — returned to the caller immediately
	repo, err := store.CreateRepository(input.Name, repoPath)
	if err != nil {
		return nil, fmt.Errorf("creating repository: %w", err)
	}

	// Persist remote URL and auth token early so they survive if the background
	// goroutine fails and the user retries via reindex.
	meta := graphstore.RepositoryMeta{}
	if isRemote {
		meta.RemoteURL = normalizeGitURL(repoPath)
		if input.Token != nil && *input.Token != "" {
			meta.AuthToken = *input.Token
		}
	}
	store.UpdateRepositoryMeta(repo.ID, meta)

	r.Resolver.publishEvent(events.EventRepoIndexStarted, map[string]interface{}{
		"repo_id": repo.ID, "repo_name": repo.Name,
	})

	// Run clone + index in the background so the HTTP request returns immediately
	// and doesn't block health probes.
	go r.importRepository(repo.ID, input.Name, repoPath, isRemote, input.Token)

	return mapRepository(repo), nil
}

// RemoveRepository is the resolver for the removeRepository field.
func (r *mutationResolver) RemoveRepository(ctx context.Context, id string) (bool, error) {
	if r.getStore(ctx) == nil {
		return false, fmt.Errorf("store not initialized")
	}
	return r.getStore(ctx).RemoveRepository(id), nil
}

// ReindexRepository is the resolver for the reindexRepository field.
func (r *mutationResolver) ReindexRepository(ctx context.Context, id string) (*Repository, error) {
	if r.getStore(ctx) == nil {
		return nil, fmt.Errorf("store not initialized")
	}

	repo := r.getStore(ctx).GetRepository(id)
	if repo == nil {
		return nil, fmt.Errorf("repository not found: %s", id)
	}

	// Determine the local source path
	var localPath string
	isRemote := isGitURL(repo.Path) || repo.RemoteURL != ""

	if isRemote {
		// Determine clone directory — prefer stored clone path, compute from config if missing
		cloneDir := repo.ClonePath
		if cloneDir == "" {
			cacheDir := "./repo-cache"
			if r.Config != nil && r.Config.Storage.RepoCachePath != "" {
				cacheDir = r.Config.Storage.RepoCachePath
			}
			cloneDir = filepath.Join(cacheDir, "repos", sanitizeRepoName(repo.Name))
		}
		localPath = cloneDir

		defaultToken, sshKeyPath := r.resolveGitCredentials()
		pullToken := repo.AuthToken
		if pullToken == "" {
			pullToken = defaultToken
		}

		// If clone directory doesn't exist, re-clone the repo
		if _, statErr := os.Stat(cloneDir); os.IsNotExist(statErr) {
			remoteURL := repo.RemoteURL
			if remoteURL == "" {
				remoteURL = repo.Path
			}
			slog.Info("re-cloning remote repo (clone missing)", "url", remoteURL, "target", cloneDir)
			if err := os.MkdirAll(filepath.Dir(cloneDir), 0o755); err != nil {
				return nil, fmt.Errorf("creating clone directory: %w", err)
			}
			cmd := gitCloneCmd(ctx, remoteURL, cloneDir, pullToken, sshKeyPath)
			if err := cmd.Run(); err != nil {
				return nil, fmt.Errorf("re-cloning repository: %w", err)
			}
			// Update stored clone path if it changed
			if repo.ClonePath != cloneDir {
				r.getStore(ctx).UpdateRepositoryMeta(id, graphstore.RepositoryMeta{ClonePath: cloneDir})
			}
		} else {
			// Pull latest changes
			slog.Info("updating remote repo", "path", localPath, "hasToken", pullToken != "")
			cmd := gitPullCmd(ctx, localPath, pullToken, sshKeyPath)
			if err := cmd.Run(); err != nil {
				slog.Warn("git pull failed, proceeding with current state", "error", err)
			}
		}
	} else {
		localPath = repo.Path
	}

	// Check that the source is accessible
	if _, err := os.Stat(localPath); err != nil {
		return nil, fmt.Errorf("repository source not accessible: %w", err)
	}

	// Snapshot symbols and commit SHA before reindex for impact analysis
	oldCommitSHA := repo.CommitSHA
	var oldSymbols []*graphstore.StoredSymbol
	oldSymbolSlice, _ := r.getStore(ctx).GetSymbols(id, nil, nil, 0, 0)
	oldSymbols = oldSymbolSlice

	// Build previous file hashes for incremental indexing
	previousHashes := make(map[string]string)
	previousFiles := make(map[string]indexer.FileResult)
	files := r.getStore(ctx).GetFiles(id)
	for _, f := range files {
		if f.ContentHash != "" {
			previousHashes[f.Path] = f.ContentHash
		}
	}

	// Re-index (incremental if we have hashes, full otherwise)
	slog.Info("reindexing repository", "id", id, "name", repo.Name, "path", localPath)
	idx := indexer.NewIndexer(nil)
	var result *indexer.IndexResult
	var err error

	if len(previousHashes) > 0 {
		result, err = idx.IndexRepositoryIncremental(ctx, localPath, previousHashes, previousFiles)
	} else {
		result, err = idx.IndexRepository(ctx, localPath)
	}
	if err != nil {
		r.getStore(ctx).SetRepositoryError(id, err)
		return nil, fmt.Errorf("reindexing repository: %w", err)
	}

	result.RepoName = repo.Name
	if isRemote {
		result.RepoPath = repo.Path
	}

	// Replace the stored data atomically
	updatedRepo, err := r.getStore(ctx).ReplaceIndexResult(id, result)
	if err != nil {
		return nil, fmt.Errorf("replacing index result: %w", err)
	}

	// Update git metadata
	meta := graphstore.RepositoryMeta{}
	if gitMeta, err := git.GetGitMetadata(localPath); err == nil && gitMeta != nil {
		meta.CommitSHA = gitMeta.CommitSHA
		meta.Branch = gitMeta.Branch
	}
	if meta.CommitSHA != "" || meta.Branch != "" {
		r.getStore(ctx).UpdateRepositoryMeta(id, meta)
	}

	updatedRepo = r.getStore(ctx).GetRepository(id)

	// Compute change impact analysis
	newCommitSHA := updatedRepo.CommitSHA
	newSymbols, _ := r.getStore(ctx).GetSymbols(id, nil, nil, 0, 0)

	// Determine changed files from git diff or fall back to full set
	var fileDiffs []graphstore.ImpactFileDiff
	changedFiles := make(map[string]bool)

	if oldCommitSHA != "" && newCommitSHA != "" && oldCommitSHA != newCommitSHA {
		if gitDiffs, err := git.DiffRefs(localPath, oldCommitSHA, newCommitSHA); err == nil {
			for _, gd := range gitDiffs {
				fileDiffs = append(fileDiffs, graphstore.ImpactFileDiff{
					Path:      gd.Path,
					OldPath:   gd.OldPath,
					Status:    string(gd.Status),
					Additions: gd.Additions,
					Deletions: gd.Deletions,
				})
				changedFiles[gd.Path] = true
				if gd.OldPath != "" {
					changedFiles[gd.OldPath] = true
				}
			}
		}
	}

	// If no git diff available, consider all files changed
	if len(changedFiles) == 0 {
		for _, f := range r.getStore(ctx).GetFiles(id) {
			changedFiles[f.Path] = true
		}
	}

	symbolChanges := graphstore.DiffSymbols(oldSymbols, newSymbols, changedFiles)
	impactReport := graphstore.ComputeImpact(r.getStore(ctx), id, fileDiffs, symbolChanges)
	impactReport.OldCommitSHA = oldCommitSHA
	impactReport.NewCommitSHA = newCommitSHA

	// Collect stale artifact IDs
	if r.KnowledgeStore != nil {
		artifacts := r.KnowledgeStore.GetKnowledgeArtifacts(id)
		for _, a := range artifacts {
			if a.Stale || a.Status != knowledgepkg.StatusReady {
				impactReport.StaleArtifacts = append(impactReport.StaleArtifacts, a.ID)
			}
		}
	}
	if impactReport.StaleArtifacts == nil {
		impactReport.StaleArtifacts = []string{}
	}

	r.getStore(ctx).StoreImpactReport(id, impactReport)
	slog.Info("impact analysis complete",
		"id", impactReport.ID,
		"filesChanged", len(impactReport.FilesChanged),
		"symbolsAdded", len(impactReport.SymbolsAdded),
		"symbolsModified", len(impactReport.SymbolsModified),
		"symbolsRemoved", len(impactReport.SymbolsRemoved),
		"affectedLinks", len(impactReport.AffectedLinks),
		"affectedRequirements", len(impactReport.AffectedRequirements),
	)

	// Mark knowledge artifacts stale after reindex
	knowledgepkg.MarkAllStale(r.KnowledgeStore, id)

	// Refresh cached understanding score
	uScore := graphstore.ComputeUnderstandingScore(r.getStore(ctx), newKnowledgeFreshnessProvider(r.KnowledgeStore), id)
	r.getStore(ctx).CacheUnderstandingScore(id, uScore.Overall)

	slog.Info("repository reindexed",
		"id", updatedRepo.ID,
		"name", updatedRepo.Name,
		"files", updatedRepo.FileCount,
		"commitSHA", updatedRepo.CommitSHA,
	)

	go r.seedRepositoryFieldGuide(id)

	return mapRepository(updatedRepo), nil
}

// ImportRequirements is the resolver for the importRequirements field.
func (r *mutationResolver) ImportRequirements(ctx context.Context, input ImportRequirementsInput) (*ImportResult, error) {
	if r.getStore(ctx) == nil {
		return nil, fmt.Errorf("store not initialized")
	}

	// Verify repository exists
	repo := r.getStore(ctx).GetRepository(input.RepositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository not found: %s", input.RepositoryID)
	}

	var parsed *requirements.ParseResult
	switch input.Format {
	case RequirementFormatMarkdown:
		parsed = requirements.ParseMarkdown(input.Content)
	case RequirementFormatCSV:
		parsed = requirements.ParseCSV(input.Content, nil)
	default:
		return nil, fmt.Errorf("unsupported format: %s", input.Format)
	}

	source := ""
	if input.SourcePath != nil {
		source = *input.SourcePath
	}

	var storedReqs []*graphstore.StoredRequirement
	skipped := 0
	for _, req := range parsed.Requirements {
		// Skip duplicates by external ID
		if existing := r.getStore(ctx).GetRequirementByExternalID(input.RepositoryID, req.ExternalID); existing != nil {
			skipped++
			continue
		}
		storedReqs = append(storedReqs, &graphstore.StoredRequirement{
			ExternalID:         req.ExternalID,
			Title:              req.Title,
			Description:        req.Description,
			Source:             source,
			Priority:           req.Priority,
			AcceptanceCriteria: req.AcceptanceCriteria,
			Tags:               req.Tags,
		})
	}

	imported := r.getStore(ctx).StoreRequirements(input.RepositoryID, storedReqs)

	// Mark knowledge artifacts stale after requirements import
	knowledgepkg.MarkAllStale(r.KnowledgeStore, input.RepositoryID)

	r.Resolver.publishEvent(events.EventRequirementImported, map[string]interface{}{
		"repo_id": input.RepositoryID, "imported": imported, "skipped": skipped,
	})

	return &ImportResult{
		Imported: imported,
		Skipped:  skipped,
		Warnings: parsed.Warnings,
	}, nil
}

// VerifyLink is the resolver for the verifyLink field.
func (r *mutationResolver) VerifyLink(ctx context.Context, linkID string, verified bool) (*RequirementLink, error) {
	if r.getStore(ctx) == nil {
		return nil, fmt.Errorf("store not initialized")
	}
	link := r.getStore(ctx).VerifyLink(linkID, verified, "graphql-user")
	if link == nil {
		return nil, fmt.Errorf("link not found: %s", linkID)
	}
	if verified {
		r.Resolver.publishEvent(events.EventLinkVerified, map[string]interface{}{"link_id": linkID})
	} else {
		r.Resolver.publishEvent(events.EventLinkRejected, map[string]interface{}{"link_id": linkID})
	}
	return mapLink(link), nil
}

// CreateManualLink is the resolver for the createManualLink field.
func (r *mutationResolver) CreateManualLink(ctx context.Context, input CreateManualLinkInput) (*RequirementLink, error) {
	if r.getStore(ctx) == nil {
		return nil, fmt.Errorf("store not initialized")
	}
	rationale := ""
	if input.Rationale != nil {
		rationale = *input.Rationale
	}
	link := r.getStore(ctx).StoreLink(input.RepositoryID, &graphstore.StoredLink{
		RequirementID: input.RequirementID,
		SymbolID:      input.SymbolID,
		Confidence:    1.0,
		Source:        "manual",
		LinkType:      "implements",
		Rationale:     rationale,
		Verified:      true,
		VerifiedBy:    "graphql-user",
	})
	return mapLink(link), nil
}

// AnalyzeSymbol is the resolver for the analyzeSymbol field.
func (r *mutationResolver) AnalyzeSymbol(ctx context.Context, repositoryID string, symbolID string) (*AnalysisResult, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable: worker not connected")
	}

	sym := r.getStore(ctx).GetSymbol(symbolID)
	if sym == nil {
		return nil, fmt.Errorf("symbol not found: %s", symbolID)
	}

	repo := r.getStore(ctx).GetRepository(repositoryID)
	repoRoot, err := resolveRepoSourcePath(repo)
	if err != nil {
		return nil, fmt.Errorf("source unavailable: %w", err)
	}

	fileContent, err := readSourceFile(repoRoot, sym.FilePath)
	if err != nil {
		return nil, fmt.Errorf("reading source: %w", err)
	}

	symbolContext := extractSymbolContext(fileContent, sym.StartLine, sym.EndLine)

	resp, err := r.Worker.AnalyzeSymbol(ctx, &reasoningv1.AnalyzeSymbolRequest{
		RepositoryId: repositoryID,
		Symbol: &commonv1.CodeSymbol{
			Id:            sym.ID,
			Name:          sym.Name,
			QualifiedName: sym.QualifiedName,
			Kind:          commonv1.SymbolKind(commonv1.SymbolKind_value["SYMBOL_KIND_"+strings.ToUpper(sym.Kind)]),
			Language:      languageToProto(sym.Language),
			Location: &commonv1.FileLocation{
				Path:      sym.FilePath,
				StartLine: int32(sym.StartLine),
				EndLine:   int32(sym.EndLine),
			},
			Signature:  sym.Signature,
			DocComment: sym.DocComment,
		},
		SurroundingContext: symbolContext,
	})
	if err != nil {
		return nil, fmt.Errorf("worker analyze failed: %w", err)
	}

	result := &AnalysisResult{
		Summary:     resp.Summary,
		Purpose:     resp.Purpose,
		Concerns:    resp.Concerns,
		Suggestions: resp.Suggestions,
	}
	if resp.Usage != nil {
		result.Model = &resp.Usage.Model
		inTok := int(resp.Usage.InputTokens)
		outTok := int(resp.Usage.OutputTokens)
		result.InputTokens = &inTok
		result.OutputTokens = &outTok
		r.getStore(ctx).StoreLLMUsage(&graphstore.LLMUsageRecord{
			RepoID: repositoryID, Provider: resp.Usage.Model, Model: resp.Usage.Model,
			Operation: "analyze_symbol", InputTokens: int(resp.Usage.InputTokens), OutputTokens: int(resp.Usage.OutputTokens),
		})
	}
	return result, nil
}

// DiscussCode is the resolver for the discussCode field.
func (r *mutationResolver) DiscussCode(ctx context.Context, input DiscussCodeInput) (*DiscussionResult, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable: worker not connected")
	}

	contextParts := make([]string, 0, 4)
	if input.ConversationHistory != nil && len(input.ConversationHistory) > 0 {
		contextParts = append(contextParts, "Recent follow-up context:\n"+strings.Join(input.ConversationHistory, "\n\n"))
	}
	if input.ArtifactID != nil && *input.ArtifactID != "" && r.KnowledgeStore != nil {
		if artifact := r.KnowledgeStore.GetKnowledgeArtifact(*input.ArtifactID); artifact != nil {
			contextParts = append(contextParts, discussionContextFromArtifact(artifact))
		}
	}

	// Prefer provided code; otherwise use indexed symbol context; finally fall back to file reads.
	var contextCode string
	if input.Code != nil && *input.Code != "" {
		contextCode = *input.Code
		contextParts = append(contextParts, contextCode)
	} else if input.SymbolID != nil && *input.SymbolID != "" {
		if sym := r.getStore(ctx).GetSymbol(*input.SymbolID); sym != nil {
			contextParts = append(contextParts, discussionContextFromStoredSymbol(sym))
			if input.FilePath == nil || *input.FilePath == "" {
				filePath := sym.FilePath
				input.FilePath = &filePath
			}
		}
	}
	if len(contextParts) == 0 && input.FilePath != nil && *input.FilePath != "" {
		repo := r.getStore(ctx).GetRepository(input.RepositoryID)
		repoRoot, err := resolveRepoSourcePath(repo)
		if err != nil {
			return nil, fmt.Errorf("source unavailable: %w", err)
		}
		content, err := readSourceFile(repoRoot, *input.FilePath)
		if err != nil {
			return nil, fmt.Errorf("reading source: %w", err)
		}
		contextParts = append(contextParts, content)
	}
	contextCode = strings.TrimSpace(strings.Join(contextParts, "\n\n"))

	if contextCode == "" {
		return nil, fmt.Errorf("provide code, filePath, artifactId, or symbolId")
	}

	lang := commonv1.Language_LANGUAGE_UNSPECIFIED
	if input.Language != nil {
		lang = languageToProto(input.Language.String())
	} else if input.FilePath != nil && *input.FilePath != "" {
		lang = deriveLanguage(*input.FilePath)
	}

	// Build context symbols from the code
	var contextSymbols []*commonv1.CodeSymbol
	if input.SymbolID != nil && *input.SymbolID != "" {
		if sym := r.getStore(ctx).GetSymbol(*input.SymbolID); sym != nil {
			contextSymbols = append(contextSymbols, protoCodeSymbolFromStored(sym))
		}
	}
	if input.FilePath != nil {
		syms := r.getStore(ctx).GetSymbolsByFile(input.RepositoryID, *input.FilePath)
		for _, s := range syms {
			contextSymbols = append(contextSymbols, &commonv1.CodeSymbol{
				Id:   s.ID,
				Name: s.Name,
			})
		}
	}

	resp, err := r.Worker.AnswerQuestion(ctx, &reasoningv1.AnswerQuestionRequest{
		Question:       input.Question,
		RepositoryId:   input.RepositoryID,
		ContextSymbols: contextSymbols,
		MaxTokens:      4096,
		ContextCode:    contextCode,
		Language:       lang,
		FilePath: func() string {
			if input.FilePath == nil {
				return ""
			}
			return *input.FilePath
		}(),
	})
	if err != nil {
		return nil, fmt.Errorf("worker discuss failed: %w", err)
	}

	result := &DiscussionResult{
		Answer:              resp.Answer,
		References:          []string{},
		RelatedRequirements: []string{},
	}
	for _, sym := range resp.ReferencedSymbols {
		result.References = append(result.References, sym.Name)
	}
	if resp.Usage != nil {
		result.Model = &resp.Usage.Model
		inTok := int(resp.Usage.InputTokens)
		outTok := int(resp.Usage.OutputTokens)
		result.InputTokens = &inTok
		result.OutputTokens = &outTok
		r.getStore(ctx).StoreLLMUsage(&graphstore.LLMUsageRecord{
			RepoID: input.RepositoryID, Provider: resp.Usage.Model, Model: resp.Usage.Model,
			Operation: "discuss_code", InputTokens: int(resp.Usage.InputTokens), OutputTokens: int(resp.Usage.OutputTokens),
		})
	}
	return result, nil
}

// ReviewCode is the resolver for the reviewCode field.
func (r *mutationResolver) ReviewCode(ctx context.Context, input ReviewCodeInput) (*ReviewResult, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable: worker not connected")
	}

	content := ""
	if input.Code != nil && *input.Code != "" {
		content = *input.Code
	} else {
		repo := r.getStore(ctx).GetRepository(input.RepositoryID)
		repoRoot, err := resolveRepoSourcePath(repo)
		if err != nil {
			return nil, fmt.Errorf("source unavailable: %w", err)
		}

		readContent, err := readSourceFile(repoRoot, input.FilePath)
		if err != nil {
			return nil, fmt.Errorf("reading source: %w", err)
		}
		content = readContent
	}

	lang := deriveLanguage(input.FilePath)
	if input.Language != nil {
		lang = languageToProto(input.Language.String())
	}

	resp, err := r.Worker.ReviewFile(ctx, &reasoningv1.ReviewFileRequest{
		RepositoryId: input.RepositoryID,
		FilePath:     input.FilePath,
		Language:     lang,
		Content:      content,
		Template:     input.Template,
	})
	if err != nil {
		return nil, fmt.Errorf("worker review failed: %w", err)
	}

	result := &ReviewResult{
		Template: resp.Template,
		Score:    float64(resp.Score),
		Findings: make([]*ReviewFinding, 0, len(resp.Findings)),
	}
	for _, f := range resp.Findings {
		finding := &ReviewFinding{
			Category: f.Category,
			Severity: f.Severity,
			Message:  f.Message,
		}
		if f.FilePath != "" {
			finding.FilePath = &f.FilePath
		}
		if f.StartLine > 0 {
			sl := int(f.StartLine)
			finding.StartLine = &sl
		}
		if f.EndLine > 0 {
			el := int(f.EndLine)
			finding.EndLine = &el
		}
		if f.Suggestion != "" {
			finding.Suggestion = &f.Suggestion
		}
		result.Findings = append(result.Findings, finding)
	}
	if resp.Usage != nil {
		result.Model = &resp.Usage.Model
		inTok := int(resp.Usage.InputTokens)
		outTok := int(resp.Usage.OutputTokens)
		result.InputTokens = &inTok
		result.OutputTokens = &outTok
		r.getStore(ctx).StoreLLMUsage(&graphstore.LLMUsageRecord{
			RepoID: input.RepositoryID, Provider: resp.Usage.Model, Model: resp.Usage.Model,
			Operation: "review_code", InputTokens: int(resp.Usage.InputTokens), OutputTokens: int(resp.Usage.OutputTokens),
		})
	}

	r.Resolver.publishEvent(events.EventReviewCompleted, map[string]interface{}{
		"repo_id": input.RepositoryID, "file_path": input.FilePath,
		"template": input.Template, "findings": len(result.Findings),
	})

	return result, nil
}

// AutoLinkRequirements is the resolver for the autoLinkRequirements field.
func (r *mutationResolver) AutoLinkRequirements(ctx context.Context, repositoryID string, minConfidence *float64) (*AutoLinkResult, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable: worker not connected")
	}

	repo := r.getStore(ctx).GetRepository(repositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository not found: %s", repositoryID)
	}

	repoRoot, err := resolveRepoSourcePath(repo)
	if err != nil {
		return nil, fmt.Errorf("source unavailable: %w", err)
	}

	minConf := float32(0.5)
	if minConfidence != nil {
		minConf = float32(*minConfidence)
	}

	// Load all requirements
	reqs, _ := r.getStore(ctx).GetRequirements(repositoryID, 10000, 0)
	if len(reqs) == 0 {
		return &AutoLinkResult{Links: []*RequirementLink{}}, nil
	}

	// Load candidate symbols in batches
	allSyms, _ := r.getStore(ctx).GetSymbols(repositoryID, nil, nil, 10000, 0)

	// Build candidate symbols with source content
	candidates := make([]*linkingv1.CandidateSymbol, 0, len(allSyms))
	sourceCache := make(map[string]string) // filePath -> content

	for _, sym := range allSyms {
		content, ok := sourceCache[sym.FilePath]
		if !ok {
			c, err := readSourceFile(repoRoot, sym.FilePath)
			if err != nil {
				continue // skip symbols whose source is unreadable
			}
			sourceCache[sym.FilePath] = c
			content = c
		}

		symContent := extractSymbolContext(content, sym.StartLine, sym.EndLine)
		candidates = append(candidates, &linkingv1.CandidateSymbol{
			Symbol: &commonv1.CodeSymbol{
				Id:            sym.ID,
				Name:          sym.Name,
				QualifiedName: sym.QualifiedName,
				Kind:          commonv1.SymbolKind(commonv1.SymbolKind_value["SYMBOL_KIND_"+strings.ToUpper(sym.Kind)]),
				Language:      languageToProto(sym.Language),
				Location: &commonv1.FileLocation{
					Path:      sym.FilePath,
					StartLine: int32(sym.StartLine),
					EndLine:   int32(sym.EndLine),
				},
				Signature:  sym.Signature,
				DocComment: sym.DocComment,
			},
			Content: symContent,
		})
	}

	var allLinks []*RequirementLink
	processed := 0

	// Process each requirement via repeated LinkRequirement calls
	for _, req := range reqs {
		processed++

		protoReq := &commonv1.Requirement{
			Id:          req.ID,
			ExternalId:  req.ExternalID,
			Title:       req.Title,
			Description: req.Description,
			Priority:    req.Priority,
			Tags:        req.Tags,
		}

		resp, err := r.Worker.LinkRequirement(ctx, &linkingv1.LinkRequirementRequest{
			Requirement:      protoReq,
			RepositoryId:     repositoryID,
			CandidateSymbols: candidates,
			MinConfidence:    minConf,
		})
		if err != nil {
			slog.Warn("auto-link failed for requirement", "req_id", req.ID, "error", err)
			continue
		}

		for _, link := range resp.Links {
			conf := protoConfidenceToFloat(link.Confidence)
			stored := r.getStore(ctx).StoreLink(repositoryID, &graphstore.StoredLink{
				RequirementID: link.RequirementId,
				SymbolID:      link.SymbolId,
				Confidence:    conf,
				Source:        "semantic",
				LinkType:      "implements",
				Rationale:     link.Rationale,
			})
			if stored != nil {
				allLinks = append(allLinks, mapLink(stored))
			}
		}
	}

	if allLinks == nil {
		allLinks = []*RequirementLink{}
	}

	r.Resolver.publishEvent(events.EventRequirementLinked, map[string]interface{}{
		"repo_id": repositoryID, "links_created": len(allLinks),
		"requirements_processed": processed,
	})

	return &AutoLinkResult{
		LinksCreated:          len(allLinks),
		RequirementsProcessed: processed,
		Links:                 allLinks,
	}, nil
}

// EnrichRequirement is the resolver for the enrichRequirement field.
func (r *mutationResolver) EnrichRequirement(ctx context.Context, requirementID string) (*Requirement, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable: worker not connected")
	}

	req := r.getStore(ctx).GetRequirement(requirementID)
	if req == nil {
		return nil, fmt.Errorf("requirement not found: %s", requirementID)
	}

	resp, err := r.Worker.EnrichRequirement(ctx, &requirementsv1.EnrichRequirementRequest{
		Requirement: &commonv1.Requirement{
			Id:          req.ID,
			ExternalId:  req.ExternalID,
			Title:       req.Title,
			Description: req.Description,
			Priority:    req.Priority,
			Tags:        req.Tags,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("worker enrich failed: %w", err)
	}

	// Persist the enrichment results
	newPriority := req.Priority
	if resp.SuggestedPriority != "" {
		newPriority = resp.SuggestedPriority
	}
	newTags := req.Tags
	if len(resp.SuggestedTags) > 0 {
		// Merge suggested tags with existing ones
		tagSet := make(map[string]bool)
		for _, t := range req.Tags {
			tagSet[t] = true
		}
		for _, t := range resp.SuggestedTags {
			tagSet[t] = true
		}
		newTags = make([]string, 0, len(tagSet))
		for t := range tagSet {
			newTags = append(newTags, t)
		}
	}

	updated := r.getStore(ctx).UpdateRequirement(requirementID, newPriority, newTags)
	if updated == nil {
		return nil, fmt.Errorf("failed to update requirement: %s", requirementID)
	}
	return mapRequirement(updated), nil
}

// GenerateCliffNotes is the resolver for the generateCliffNotes field.
func (r *mutationResolver) GenerateCliffNotes(ctx context.Context, input GenerateCliffNotesInput) (*KnowledgeArtifact, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable — worker not connected")
	}
	if r.KnowledgeStore == nil {
		return nil, fmt.Errorf("knowledge store not configured")
	}

	repo := r.getStore(ctx).GetRepository(input.RepositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository %s not found", input.RepositoryID)
	}
	key, err := artifactKeyFromCliffNotesInput(input)
	if err != nil {
		return nil, err
	}
	audience := string(key.Audience)
	depth := string(key.Depth)
	scope := key.Scope.Normalize()

	existing := r.KnowledgeStore.GetArtifactByKey(key)
	if existing != nil {
		if shouldRefreshScopedCliffNotes(existing) {
			_ = r.KnowledgeStore.DeleteKnowledgeArtifact(existing.ID)
			existing = nil
		}
	}
	if existing != nil {
		if existing.Status == knowledgepkg.StatusReady && !existing.Stale {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusGenerating || existing.Status == knowledgepkg.StatusPending {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusFailed || existing.Stale {
			_ = r.KnowledgeStore.DeleteKnowledgeArtifact(existing.ID)
		}
	}

	// Assemble snapshot — repo source is optional (docs will be omitted if unavailable).
	assembler := knowledgepkg.NewAssembler(r.getStore(ctx))
	repoRoot, repoRootErr := resolveRepoSourcePath(repo)
	if repoRootErr != nil {
		slog.Warn("cliff notes: repo source unavailable, docs will be omitted from snapshot",
			"repo_id", repo.ID, "error", repoRootErr)
	}
	var snap *knowledgepkg.KnowledgeSnapshot
	if scope.ScopeType == knowledgepkg.ScopeRepository {
		snap, err = assembler.Assemble(repo.ID, repoRoot)
	} else {
		snap, err = assembler.AssembleScoped(repo.ID, repoRoot, scope)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to assemble knowledge snapshot: %w", err)
	}

	snapJSON, err := json.Marshal(snap)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize snapshot: %w", err)
	}

	artifact, created, err := r.KnowledgeStore.ClaimArtifact(key, snap.SourceRevision)
	if err != nil {
		return nil, fmt.Errorf("failed to claim knowledge artifact: %w", err)
	}
	if !created {
		return mapKnowledgeArtifact(artifact), nil
	}

	// Run LLM generation async — return immediately so the proxy doesn't timeout.
	// The UI polls knowledgeArtifacts to check status and progress.
	store := r.getStore(ctx)
	go func() {
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.1) // snapshot ready
		bgCtx := context.Background()
		resp, err := r.Worker.GenerateCliffNotes(bgCtx, &knowledgev1.GenerateCliffNotesRequest{
			RepositoryId:   repo.ID,
			RepositoryName: repo.Name,
			Audience:       audience,
			Depth:          depth,
			ScopeType:      string(scope.ScopeType),
			ScopePath:      scope.ScopePath,
			SnapshotJson:   string(snapJSON),
		})
		if err != nil {
			slog.Error("cliff notes generation failed", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.8) // LLM complete

		// Store LLM usage
		if resp.Usage != nil {
			store.StoreLLMUsage(&graphstore.LLMUsageRecord{
				RepoID:       repo.ID,
				Provider:     "llm",
				Model:        resp.Usage.Model,
				Operation:    resp.Usage.Operation,
				InputTokens:  int(resp.Usage.InputTokens),
				OutputTokens: int(resp.Usage.OutputTokens),
			})
		}

		// Persist sections
		sections := make([]knowledgepkg.Section, len(resp.Sections))
		for i, sec := range resp.Sections {
			sections[i] = knowledgepkg.Section{
				Title:      sec.Title,
				Content:    sec.Content,
				Summary:    sec.Summary,
				Confidence: mapProtoConfidence(sec.Confidence),
				Inferred:   sec.Inferred,
			}
		}
		if err := r.KnowledgeStore.StoreKnowledgeSections(artifact.ID, sections); err != nil {
			slog.Error("failed to store cliff notes sections", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}

		// Persist evidence for each section
		storedSections := r.KnowledgeStore.GetKnowledgeSections(artifact.ID)
		for i, sec := range resp.Sections {
			if i >= len(storedSections) {
				break
			}
			if len(sec.Evidence) > 0 {
				evidence := make([]knowledgepkg.Evidence, len(sec.Evidence))
				for j, ev := range sec.Evidence {
					evidence[j] = knowledgepkg.Evidence{
						SourceType: knowledgepkg.EvidenceSourceType(ev.SourceType),
						SourceID:   ev.SourceId,
						FilePath:   ev.FilePath,
						LineStart:  int(ev.LineStart),
						LineEnd:    int(ev.LineEnd),
						Rationale:  ev.Rationale,
					}
				}
				_ = r.KnowledgeStore.StoreKnowledgeEvidence(storedSections[i].ID, evidence)
			}
		}

		// Mark ready
		if err := r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusReady); err != nil {
			slog.Error("failed to mark cliff notes ready", "artifact_id", artifact.ID, "error", err)
		}
		slog.Info("cliff notes generation complete", "artifact_id", artifact.ID)
	}()

	// Return immediately with GENERATING status
	return mapKnowledgeArtifact(artifact), nil
}

// GenerateLearningPath is the resolver for the generateLearningPath field.
func (r *mutationResolver) GenerateLearningPath(ctx context.Context, input GenerateLearningPathInput) (*KnowledgeArtifact, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable — worker not connected")
	}
	if r.KnowledgeStore == nil {
		return nil, fmt.Errorf("knowledge store not configured")
	}

	repo := r.getStore(ctx).GetRepository(input.RepositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository %s not found", input.RepositoryID)
	}

	audience := "developer"
	if input.Audience != nil {
		audience = strings.ToLower(string(*input.Audience))
	}
	depth := "medium"
	if input.Depth != nil {
		depth = strings.ToLower(string(*input.Depth))
	}
	focusArea := ""
	if input.FocusArea != nil {
		focusArea = *input.FocusArea
	}

	// Assemble snapshot
	assembler := knowledgepkg.NewAssembler(r.getStore(ctx))
	repoRoot, repoRootErr := resolveRepoSourcePath(repo)
	if repoRootErr != nil {
		slog.Warn("repo source unavailable, docs will be omitted", "repo_id", repo.ID, "error", repoRootErr)
	}
	snap, err := assembler.Assemble(repo.ID, repoRoot)
	if err != nil {
		return nil, fmt.Errorf("failed to assemble knowledge snapshot: %w", err)
	}

	snapJSON, err := json.Marshal(snap)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize snapshot: %w", err)
	}
	key := knowledgepkg.ArtifactKey{
		RepositoryID: repo.ID,
		Type:         knowledgepkg.ArtifactLearningPath,
		Audience:     knowledgepkg.Audience(audience),
		Depth:        knowledgepkg.Depth(depth),
		Scope:        knowledgepkg.ArtifactScope{ScopeType: knowledgepkg.ScopeRepository},
	}.Normalized()
	if existing := r.KnowledgeStore.GetArtifactByKey(key); existing != nil {
		if existing.Status == knowledgepkg.StatusReady && !existing.Stale {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusGenerating || existing.Status == knowledgepkg.StatusPending {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusFailed || existing.Stale {
			_ = r.KnowledgeStore.DeleteKnowledgeArtifact(existing.ID)
		}
	}
	artifact, created, err := r.KnowledgeStore.ClaimArtifact(key, snap.SourceRevision)
	if err != nil {
		return nil, fmt.Errorf("failed to claim knowledge artifact: %w", err)
	}
	if !created {
		return mapKnowledgeArtifact(artifact), nil
	}

	// Run LLM generation async
	store := r.getStore(ctx)
	go func() {
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.1)
		bgCtx := context.Background()
		resp, err := r.Worker.GenerateLearningPath(bgCtx, &knowledgev1.GenerateLearningPathRequest{
			RepositoryId:   repo.ID,
			RepositoryName: repo.Name,
			Audience:       audience,
			Depth:          depth,
			SnapshotJson:   string(snapJSON),
			FocusArea:      focusArea,
		})
		if err != nil {
			slog.Error("learning path generation failed", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.8)

		if resp.Usage != nil {
			store.StoreLLMUsage(&graphstore.LLMUsageRecord{
				RepoID:       repo.ID,
				Provider:     "llm",
				Model:        resp.Usage.Model,
				Operation:    resp.Usage.Operation,
				InputTokens:  int(resp.Usage.InputTokens),
				OutputTokens: int(resp.Usage.OutputTokens),
			})
		}

		sections := make([]knowledgepkg.Section, len(resp.Steps))
		for i, step := range resp.Steps {
			sections[i] = knowledgepkg.Section{
				Title:      step.Title,
				Content:    step.Content,
				Summary:    step.Objective,
				Confidence: knowledgepkg.ConfidenceMedium,
			}
		}
		if err := r.KnowledgeStore.StoreKnowledgeSections(artifact.ID, sections); err != nil {
			slog.Error("failed to store learning path sections", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}

		storedSections := r.KnowledgeStore.GetKnowledgeSections(artifact.ID)
		for i, step := range resp.Steps {
			if i >= len(storedSections) {
				break
			}
			var evidence []knowledgepkg.Evidence
			for _, fp := range step.FilePaths {
				evidence = append(evidence, knowledgepkg.Evidence{
					SourceType: knowledgepkg.EvidenceFile,
					FilePath:   fp,
					Rationale:  "Referenced in learning step",
				})
			}
			for _, sid := range step.SymbolIds {
				evidence = append(evidence, knowledgepkg.Evidence{
					SourceType: knowledgepkg.EvidenceSymbol,
					SourceID:   sid,
					Rationale:  "Referenced in learning step",
				})
			}
			if len(evidence) > 0 {
				_ = r.KnowledgeStore.StoreKnowledgeEvidence(storedSections[i].ID, evidence)
			}
		}

		if err := r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusReady); err != nil {
			slog.Error("failed to mark learning path ready", "artifact_id", artifact.ID, "error", err)
		}
		slog.Info("learning path generation complete", "artifact_id", artifact.ID)
	}()

	return mapKnowledgeArtifact(artifact), nil
}

// GenerateCodeTour is the resolver for the generateCodeTour field.
func (r *mutationResolver) GenerateCodeTour(ctx context.Context, input GenerateCodeTourInput) (*KnowledgeArtifact, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable — worker not connected")
	}
	if r.KnowledgeStore == nil {
		return nil, fmt.Errorf("knowledge store not configured")
	}

	repo := r.getStore(ctx).GetRepository(input.RepositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository %s not found", input.RepositoryID)
	}

	audience := "developer"
	if input.Audience != nil {
		audience = strings.ToLower(string(*input.Audience))
	}
	depth := "medium"
	if input.Depth != nil {
		depth = strings.ToLower(string(*input.Depth))
	}
	theme := ""
	if input.Theme != nil {
		theme = *input.Theme
	}

	assembler := knowledgepkg.NewAssembler(r.getStore(ctx))
	repoRoot, repoRootErr := resolveRepoSourcePath(repo)
	if repoRootErr != nil {
		slog.Warn("repo source unavailable, docs will be omitted", "repo_id", repo.ID, "error", repoRootErr)
	}
	snap, err := assembler.Assemble(repo.ID, repoRoot)
	if err != nil {
		return nil, fmt.Errorf("failed to assemble knowledge snapshot: %w", err)
	}

	snapJSON, err := json.Marshal(snap)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize snapshot: %w", err)
	}
	key := knowledgepkg.ArtifactKey{
		RepositoryID: repo.ID,
		Type:         knowledgepkg.ArtifactCodeTour,
		Audience:     knowledgepkg.Audience(audience),
		Depth:        knowledgepkg.Depth(depth),
		Scope:        knowledgepkg.ArtifactScope{ScopeType: knowledgepkg.ScopeRepository},
	}.Normalized()
	if existing := r.KnowledgeStore.GetArtifactByKey(key); existing != nil {
		if existing.Status == knowledgepkg.StatusReady && !existing.Stale {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusGenerating || existing.Status == knowledgepkg.StatusPending {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusFailed || existing.Stale {
			_ = r.KnowledgeStore.DeleteKnowledgeArtifact(existing.ID)
		}
	}
	artifact, created, err := r.KnowledgeStore.ClaimArtifact(key, snap.SourceRevision)
	if err != nil {
		return nil, fmt.Errorf("failed to claim knowledge artifact: %w", err)
	}
	if !created {
		return mapKnowledgeArtifact(artifact), nil
	}

	// Run LLM generation async
	store := r.getStore(ctx)
	go func() {
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.1)
		bgCtx := context.Background()
		resp, err := r.Worker.GenerateCodeTour(bgCtx, &knowledgev1.GenerateCodeTourRequest{
			RepositoryId:   repo.ID,
			RepositoryName: repo.Name,
			Audience:       audience,
			Depth:          depth,
			SnapshotJson:   string(snapJSON),
			Theme:          theme,
		})
		if err != nil {
			slog.Error("code tour generation failed", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.8)

		if resp.Usage != nil {
			store.StoreLLMUsage(&graphstore.LLMUsageRecord{
				RepoID:       repo.ID,
				Provider:     "llm",
				Model:        resp.Usage.Model,
				Operation:    resp.Usage.Operation,
				InputTokens:  int(resp.Usage.InputTokens),
				OutputTokens: int(resp.Usage.OutputTokens),
			})
		}

		sections := make([]knowledgepkg.Section, len(resp.Stops))
		for i, stop := range resp.Stops {
			sections[i] = knowledgepkg.Section{
				Title:      stop.Title,
				Content:    stop.Description,
				Confidence: knowledgepkg.ConfidenceMedium,
			}
		}
		if err := r.KnowledgeStore.StoreKnowledgeSections(artifact.ID, sections); err != nil {
			slog.Error("failed to store code tour sections", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}

		storedSections := r.KnowledgeStore.GetKnowledgeSections(artifact.ID)
		for i, stop := range resp.Stops {
			if i >= len(storedSections) {
				break
			}
			if stop.FilePath != "" {
				_ = r.KnowledgeStore.StoreKnowledgeEvidence(storedSections[i].ID, []knowledgepkg.Evidence{
					{
						SourceType: knowledgepkg.EvidenceFile,
						FilePath:   stop.FilePath,
						LineStart:  int(stop.LineStart),
						LineEnd:    int(stop.LineEnd),
						Rationale:  "Code tour stop location",
					},
				})
			}
		}

		if err := r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusReady); err != nil {
			slog.Error("failed to mark code tour ready", "artifact_id", artifact.ID, "error", err)
		}
		slog.Info("code tour generation complete", "artifact_id", artifact.ID)
	}()

	return mapKnowledgeArtifact(artifact), nil
}

// GenerateWorkflowStory is the resolver for the generateWorkflowStory field.
func (r *mutationResolver) GenerateWorkflowStory(ctx context.Context, input GenerateWorkflowStoryInput) (*KnowledgeArtifact, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable — worker not connected")
	}
	if r.KnowledgeStore == nil {
		return nil, fmt.Errorf("knowledge store not configured")
	}

	repo := r.getStore(ctx).GetRepository(input.RepositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository %s not found", input.RepositoryID)
	}
	key, err := artifactKeyFromWorkflowStoryInput(input)
	if err != nil {
		return nil, err
	}
	audience := string(key.Audience)
	depth := string(key.Depth)
	scope := key.Scope.Normalize()

	existing := r.KnowledgeStore.GetArtifactByKey(key)
	if existing != nil {
		if existing.Status == knowledgepkg.StatusReady && !existing.Stale {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusGenerating || existing.Status == knowledgepkg.StatusPending {
			return mapKnowledgeArtifact(existing), nil
		}
		if existing.Status == knowledgepkg.StatusFailed || existing.Stale {
			_ = r.KnowledgeStore.DeleteKnowledgeArtifact(existing.ID)
		}
	}

	assembler := knowledgepkg.NewAssembler(r.getStore(ctx))
	repoRoot, repoRootErr := resolveRepoSourcePath(repo)
	if repoRootErr != nil {
		slog.Warn("workflow story: repo source unavailable, docs will be omitted from snapshot",
			"repo_id", repo.ID, "error", repoRootErr)
	}
	var snap *knowledgepkg.KnowledgeSnapshot
	if scope.ScopeType == knowledgepkg.ScopeRepository {
		snap, err = assembler.Assemble(repo.ID, repoRoot)
	} else {
		snap, err = assembler.AssembleScoped(repo.ID, repoRoot, scope)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to assemble knowledge snapshot: %w", err)
	}

	snapJSON, err := json.Marshal(snap)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize snapshot: %w", err)
	}

	artifact, created, err := r.KnowledgeStore.ClaimArtifact(key, snap.SourceRevision)
	if err != nil {
		return nil, fmt.Errorf("failed to claim knowledge artifact: %w", err)
	}
	if !created {
		return mapKnowledgeArtifact(artifact), nil
	}

	anchorLabel := ""
	if input.AnchorLabel != nil {
		anchorLabel = strings.TrimSpace(*input.AnchorLabel)
	}
	executionPathJSON := ""
	if input.ExecutionPathJSON != nil {
		executionPathJSON = strings.TrimSpace(*input.ExecutionPathJSON)
	}

	store := r.getStore(ctx)
	go func() {
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.1)
		bgCtx := context.Background()
		resp, err := r.Worker.GenerateWorkflowStory(bgCtx, &knowledgev1.GenerateWorkflowStoryRequest{
			RepositoryId:      repo.ID,
			RepositoryName:    repo.Name,
			Audience:          audience,
			Depth:             depth,
			ScopeType:         string(scope.ScopeType),
			ScopePath:         scope.ScopePath,
			AnchorLabel:       anchorLabel,
			ExecutionPathJson: executionPathJSON,
			SnapshotJson:      string(snapJSON),
		})
		if err != nil {
			slog.Error("workflow story generation failed", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(artifact.ID, 0.8)

		if resp.Usage != nil {
			store.StoreLLMUsage(&graphstore.LLMUsageRecord{
				RepoID:       repo.ID,
				Provider:     "llm",
				Model:        resp.Usage.Model,
				Operation:    resp.Usage.Operation,
				InputTokens:  int(resp.Usage.InputTokens),
				OutputTokens: int(resp.Usage.OutputTokens),
			})
		}

		sections := make([]knowledgepkg.Section, len(resp.Sections))
		for i, sec := range resp.Sections {
			sections[i] = knowledgepkg.Section{
				Title:      sec.Title,
				Content:    sec.Content,
				Summary:    sec.Summary,
				Confidence: mapProtoConfidence(sec.Confidence),
				Inferred:   sec.Inferred,
			}
		}
		if err := r.KnowledgeStore.StoreKnowledgeSections(artifact.ID, sections); err != nil {
			slog.Error("failed to store workflow story sections", "artifact_id", artifact.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusFailed)
			return
		}

		storedSections := r.KnowledgeStore.GetKnowledgeSections(artifact.ID)
		for i, sec := range resp.Sections {
			if i >= len(storedSections) {
				break
			}
			if len(sec.Evidence) > 0 {
				_ = r.KnowledgeStore.StoreKnowledgeEvidence(storedSections[i].ID, mapProtoEvidence(sec.Evidence))
			}
		}

		if err := r.KnowledgeStore.UpdateKnowledgeArtifactStatus(artifact.ID, knowledgepkg.StatusReady); err != nil {
			slog.Error("failed to mark workflow story ready", "artifact_id", artifact.ID, "error", err)
		}
		slog.Info("workflow story generation complete", "artifact_id", artifact.ID)
	}()

	return mapKnowledgeArtifact(artifact), nil
}

// ExplainSystem is the resolver for the explainSystem field.
func (r *mutationResolver) ExplainSystem(ctx context.Context, input ExplainSystemInput) (*ExplainSystemResult, error) {
	if r.Worker == nil {
		return nil, fmt.Errorf("AI features are unavailable — worker not connected")
	}

	repo := r.getStore(ctx).GetRepository(input.RepositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository %s not found", input.RepositoryID)
	}

	audience := "developer"
	if input.Audience != nil {
		audience = strings.ToLower(string(*input.Audience))
	}
	question := ""
	if input.Question != nil {
		question = *input.Question
	}

	assembler := knowledgepkg.NewAssembler(r.getStore(ctx))
	scope, err := artifactScopeFromInput(input.ScopeType, input.ScopePath)
	if err != nil {
		return nil, err
	}
	repoRoot, repoRootErr := resolveRepoSourcePath(repo)
	if repoRootErr != nil {
		slog.Warn("repo source unavailable, docs will be omitted", "repo_id", repo.ID, "error", repoRootErr)
	}
	var snap *knowledgepkg.KnowledgeSnapshot
	if scope.ScopeType == knowledgepkg.ScopeRepository {
		snap, err = assembler.Assemble(repo.ID, repoRoot)
	} else {
		snap, err = assembler.AssembleScoped(repo.ID, repoRoot, scope)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to assemble knowledge snapshot: %w", err)
	}

	snapJSON, err := json.Marshal(snap)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize snapshot: %w", err)
	}

	resp, err := r.Worker.ExplainSystem(ctx, &knowledgev1.ExplainSystemRequest{
		RepositoryId:   repo.ID,
		RepositoryName: repo.Name,
		Audience:       audience,
		Question:       question,
		ScopeType:      string(scope.ScopeType),
		ScopePath:      scope.ScopePath,
		SnapshotJson:   string(snapJSON),
	})
	if err != nil {
		return nil, fmt.Errorf("system explanation failed: %w", err)
	}

	if resp.Usage != nil {
		r.getStore(ctx).StoreLLMUsage(&graphstore.LLMUsageRecord{
			RepoID:       repo.ID,
			Provider:     "llm",
			Model:        resp.Usage.Model,
			Operation:    resp.Usage.Operation,
			InputTokens:  int(resp.Usage.InputTokens),
			OutputTokens: int(resp.Usage.OutputTokens),
		})
	}

	result := &ExplainSystemResult{
		Explanation: resp.Explanation,
	}
	if resp.Usage != nil {
		model := resp.Usage.Model
		inputTokens := int(resp.Usage.InputTokens)
		outputTokens := int(resp.Usage.OutputTokens)
		result.Model = &model
		result.InputTokens = &inputTokens
		result.OutputTokens = &outputTokens
	}
	return result, nil
}

// RefreshKnowledgeArtifact is the resolver for the refreshKnowledgeArtifact field.
func (r *mutationResolver) RefreshKnowledgeArtifact(ctx context.Context, id string) (*KnowledgeArtifact, error) {
	if r.KnowledgeStore == nil {
		return nil, fmt.Errorf("knowledge store not configured")
	}

	existing := r.KnowledgeStore.GetKnowledgeArtifact(id)
	if existing == nil {
		return nil, fmt.Errorf("knowledge artifact %s not found", id)
	}
	repo := r.getStore(ctx).GetRepository(existing.RepositoryID)
	if repo == nil {
		return nil, fmt.Errorf("repository %s not found", existing.RepositoryID)
	}
	if err := r.KnowledgeStore.UpdateKnowledgeArtifactProgress(id, 0); err != nil {
		return nil, err
	}
	if err := r.KnowledgeStore.UpdateKnowledgeArtifactStatus(id, knowledgepkg.StatusGenerating); err != nil {
		return nil, err
	}

	scope := knowledgepkg.ArtifactScope{ScopeType: knowledgepkg.ScopeRepository}
	if existing.Scope != nil {
		scope = existing.Scope.Normalize()
	}
	assembler := knowledgepkg.NewAssembler(r.getStore(ctx))
	repoRoot, repoRootErr := resolveRepoSourcePath(repo)
	if repoRootErr != nil {
		slog.Warn("refresh: repo source unavailable, docs will be omitted", "repo_id", repo.ID, "error", repoRootErr)
	}

	go func(existing *knowledgepkg.Artifact) {
		var (
			snap *knowledgepkg.KnowledgeSnapshot
			err  error
		)
		if scope.ScopeType == knowledgepkg.ScopeRepository {
			snap, err = assembler.Assemble(repo.ID, repoRoot)
		} else {
			snap, err = assembler.AssembleScoped(repo.ID, repoRoot, scope)
		}
		if err != nil {
			slog.Error("refresh assemble failed", "artifact_id", existing.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
			return
		}
		snapJSON, err := json.Marshal(snap)
		if err != nil {
			slog.Error("refresh serialize failed", "artifact_id", existing.ID, "error", err)
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
			return
		}
		_ = r.KnowledgeStore.UpdateKnowledgeArtifactProgress(existing.ID, 0.1)

		switch existing.Type {
		case knowledgepkg.ArtifactCliffNotes:
			resp, err := r.Worker.GenerateCliffNotes(context.Background(), &knowledgev1.GenerateCliffNotesRequest{
				RepositoryId:   repo.ID,
				RepositoryName: repo.Name,
				Audience:       string(existing.Audience),
				Depth:          string(existing.Depth),
				ScopeType:      string(scope.ScopeType),
				ScopePath:      scope.ScopePath,
				SnapshotJson:   string(snapJSON),
			})
			if err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
			sections := make([]knowledgepkg.Section, len(resp.Sections))
			for i, sec := range resp.Sections {
				sections[i] = knowledgepkg.Section{
					Title:      sec.Title,
					Content:    sec.Content,
					Summary:    sec.Summary,
					Confidence: mapProtoConfidence(sec.Confidence),
					Inferred:   sec.Inferred,
					Evidence:   mapProtoEvidence(sec.Evidence),
				}
			}
			if err := r.KnowledgeStore.SupersedeArtifact(existing.ID, sections); err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
		case knowledgepkg.ArtifactLearningPath:
			resp, err := r.Worker.GenerateLearningPath(context.Background(), &knowledgev1.GenerateLearningPathRequest{
				RepositoryId:   repo.ID,
				RepositoryName: repo.Name,
				Audience:       string(existing.Audience),
				Depth:          string(existing.Depth),
				SnapshotJson:   string(snapJSON),
			})
			if err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
			sections := make([]knowledgepkg.Section, len(resp.Steps))
			for i, step := range resp.Steps {
				sections[i] = knowledgepkg.Section{
					Title:      step.Title,
					Content:    step.Content,
					Summary:    step.Objective,
					Confidence: knowledgepkg.ConfidenceMedium,
				}
			}
			if err := r.KnowledgeStore.SupersedeArtifact(existing.ID, sections); err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
		case knowledgepkg.ArtifactCodeTour:
			resp, err := r.Worker.GenerateCodeTour(context.Background(), &knowledgev1.GenerateCodeTourRequest{
				RepositoryId:   repo.ID,
				RepositoryName: repo.Name,
				Audience:       string(existing.Audience),
				Depth:          string(existing.Depth),
				SnapshotJson:   string(snapJSON),
			})
			if err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
			sections := make([]knowledgepkg.Section, len(resp.Stops))
			for i, stop := range resp.Stops {
				sections[i] = knowledgepkg.Section{
					Title:      stop.Title,
					Content:    stop.Description,
					Summary:    stop.FilePath,
					Confidence: knowledgepkg.ConfidenceMedium,
					Evidence: []knowledgepkg.Evidence{{
						SourceType: knowledgepkg.EvidenceFile,
						FilePath:   stop.FilePath,
						LineStart:  int(stop.LineStart),
						LineEnd:    int(stop.LineEnd),
					}},
				}
			}
			if err := r.KnowledgeStore.SupersedeArtifact(existing.ID, sections); err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
		case knowledgepkg.ArtifactWorkflowStory:
			resp, err := r.Worker.GenerateWorkflowStory(context.Background(), &knowledgev1.GenerateWorkflowStoryRequest{
				RepositoryId:   repo.ID,
				RepositoryName: repo.Name,
				Audience:       string(existing.Audience),
				Depth:          string(existing.Depth),
				ScopeType:      string(scope.ScopeType),
				ScopePath:      scope.ScopePath,
				SnapshotJson:   string(snapJSON),
			})
			if err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
			sections := make([]knowledgepkg.Section, len(resp.Sections))
			for i, sec := range resp.Sections {
				sections[i] = knowledgepkg.Section{
					Title:      sec.Title,
					Content:    sec.Content,
					Summary:    sec.Summary,
					Confidence: mapProtoConfidence(sec.Confidence),
					Inferred:   sec.Inferred,
					Evidence:   mapProtoEvidence(sec.Evidence),
				}
			}
			if err := r.KnowledgeStore.SupersedeArtifact(existing.ID, sections); err != nil {
				_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
				return
			}
		default:
			_ = r.KnowledgeStore.UpdateKnowledgeArtifactStatus(existing.ID, knowledgepkg.StatusFailed)
			return
		}
	}(existing)

	updated := r.KnowledgeStore.GetKnowledgeArtifact(id)
	return mapKnowledgeArtifact(updated), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*HealthStatus, error) {
	services := []*ServiceHealth{
		{Name: "api", Status: "healthy"},
	}

	// Check database
	dbStatus := "healthy"
	if r.getStore(ctx) == nil {
		dbStatus = "unavailable"
	}
	services = append(services, &ServiceHealth{Name: "database", Status: dbStatus})

	// Check worker
	workerStatus := "unavailable"
	if r.Worker != nil {
		healthy, err := r.Worker.CheckHealth(ctx)
		if err == nil && healthy {
			workerStatus = "healthy"
		} else if err != nil {
			workerStatus = "unhealthy"
		}
	}
	services = append(services, &ServiceHealth{Name: "worker", Status: workerStatus})

	overallStatus := "healthy"
	if dbStatus != "healthy" {
		overallStatus = "degraded"
	}

	return &HealthStatus{
		Status:   overallStatus,
		Services: services,
	}, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (*VersionInfo, error) {
	return &VersionInfo{
		Version:   version.Version,
		Commit:    version.Commit,
		BuildDate: version.BuildDate,
	}, nil
}

// Features is the resolver for the features field.
func (r *queryResolver) Features(ctx context.Context) (*Features, error) {
	return r.resolveCapabilities().features, nil
}

// IdeCapabilities is the resolver for the ideCapabilities field.
func (r *queryResolver) IdeCapabilities(ctx context.Context) (*IDECapabilities, error) {
	return r.resolveCapabilities().ideCapabilities, nil
}

// Repositories is the resolver for the repositories field.
func (r *queryResolver) Repositories(ctx context.Context) ([]*Repository, error) {
	if r.getStore(ctx) == nil {
		return []*Repository{}, nil
	}

	store := r.getStore(ctx)
	graphRepos := store.ListRepositories()
	var repos []*Repository
	for _, gr := range graphRepos {
		repo := mapRepository(gr)
		_, reqCount := store.GetRequirements(gr.ID, 0, 0)
		repo.RequirementCount = reqCount
		repos = append(repos, repo)
	}
	return repos, nil
}

// Repository is the resolver for the repository field.
func (r *queryResolver) Repository(ctx context.Context, id string) (*Repository, error) {
	if r.getStore(ctx) == nil {
		return nil, fmt.Errorf("store not initialized")
	}

	gr := r.getStore(ctx).GetRepository(id)
	if gr == nil {
		return nil, fmt.Errorf("repository not found: %s", id)
	}
	store := r.getStore(ctx)
	repo := mapRepository(gr)
	_, reqCount := store.GetRequirements(gr.ID, 0, 0)
	repo.RequirementCount = reqCount
	populateRepositoryDetails(repo, store)
	return repo, nil
}

// Symbols is the resolver for the symbols field.
func (r *queryResolver) Symbols(ctx context.Context, repositoryID string, query *string, filePath *string, kind *SymbolKind, limit *int, offset *int) (*SymbolConnection, error) {
	if r.getStore(ctx) == nil {
		return &SymbolConnection{Nodes: []*CodeSymbol{}, TotalCount: 0}, nil
	}

	// If filePath is provided, use the file-based lookup
	if filePath != nil && *filePath != "" {
		syms := r.getStore(ctx).GetSymbolsByFile(repositoryID, *filePath)
		var nodes []*CodeSymbol
		for _, s := range syms {
			if kind != nil {
				k := strings.ToLower(string(*kind))
				if s.Kind != k {
					continue
				}
			}
			sym := mapSymbol(s)
			populateSymbolRelations(sym, r.getStore(ctx))
			nodes = append(nodes, sym)
		}
		return &SymbolConnection{Nodes: nodes, TotalCount: len(nodes)}, nil
	}

	var kindStr *string
	if kind != nil {
		s := strings.ToLower(string(*kind))
		kindStr = &s
	}
	lim := 100
	off := 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}

	var queryStr *string
	if query != nil {
		queryStr = query
	}

	syms, total := r.getStore(ctx).GetSymbols(repositoryID, queryStr, kindStr, lim, off)
	var nodes []*CodeSymbol
	for _, s := range syms {
		sym := mapSymbol(s)
		populateSymbolRelations(sym, r.getStore(ctx))
		nodes = append(nodes, sym)
	}
	return &SymbolConnection{Nodes: nodes, TotalCount: total}, nil
}

// Requirements is the resolver for the requirements field.
func (r *queryResolver) Requirements(ctx context.Context, repositoryID string, limit *int, offset *int) (*RequirementConnection, error) {
	if r.getStore(ctx) == nil {
		return &RequirementConnection{Nodes: []*Requirement{}, TotalCount: 0}, nil
	}

	lim := 100
	off := 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}

	reqs, total := r.getStore(ctx).GetRequirements(repositoryID, lim, off)
	var nodes []*Requirement
	for _, req := range reqs {
		nodes = append(nodes, mapRequirement(req))
	}
	return &RequirementConnection{Nodes: nodes, TotalCount: total}, nil
}

// Requirement is the resolver for the requirement field.
func (r *queryResolver) Requirement(ctx context.Context, id string) (*Requirement, error) {
	if r.getStore(ctx) == nil {
		return nil, fmt.Errorf("store not initialized")
	}
	req := r.getStore(ctx).GetRequirement(id)
	if req == nil {
		return nil, fmt.Errorf("requirement not found: %s", id)
	}
	mapped := mapRequirement(req)
	populateRequirementLinks(mapped, r.getStore(ctx))
	return mapped, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, repositoryID *string, limit *int) ([]*SearchResult, error) {
	if r.getStore(ctx) == nil {
		return []*SearchResult{}, nil
	}

	maxResults := 50
	if limit != nil && *limit > 0 && *limit < 200 {
		maxResults = *limit
	}

	var results []*SearchResult
	queryLower := strings.ToLower(query)

	// Search across all repositories
	repos := r.getStore(ctx).ListRepositories()
	for _, repo := range repos {
		if repositoryID != nil && *repositoryID != "" && repo.ID != *repositoryID {
			continue
		}

		// Search symbols
		symbols, _ := r.getStore(ctx).GetSymbols(repo.ID, nil, nil, 0, 0)
		for _, sym := range symbols {
			if len(results) >= maxResults {
				break
			}
			nameLower := strings.ToLower(sym.Name)
			qualLower := strings.ToLower(sym.QualifiedName)
			if strings.Contains(nameLower, queryLower) || strings.Contains(qualLower, queryLower) {
				fp := sym.FilePath
				sl := sym.StartLine
				results = append(results, &SearchResult{
					Type:           "symbol",
					ID:             sym.ID,
					Title:          sym.Name,
					Description:    &sym.QualifiedName,
					FilePath:       &fp,
					Line:           &sl,
					RepositoryID:   repo.ID,
					RepositoryName: repo.Name,
				})
			}
		}

		// Search requirements
		reqs, _ := r.getStore(ctx).GetRequirements(repo.ID, 0, 0)
		for _, req := range reqs {
			if len(results) >= maxResults {
				break
			}
			titleLower := strings.ToLower(req.Title)
			descLower := strings.ToLower(req.Description)
			extLower := strings.ToLower(req.ExternalID)
			if strings.Contains(titleLower, queryLower) || strings.Contains(descLower, queryLower) || strings.Contains(extLower, queryLower) {
				desc := req.Description
				results = append(results, &SearchResult{
					Type:           "requirement",
					ID:             req.ID,
					Title:          req.ExternalID + ": " + req.Title,
					Description:    &desc,
					RepositoryID:   repo.ID,
					RepositoryName: repo.Name,
				})
			}
		}

		// Search files
		files := r.getStore(ctx).GetFiles(repo.ID)
		for _, f := range files {
			if len(results) >= maxResults {
				break
			}
			pathLower := strings.ToLower(f.Path)
			if strings.Contains(pathLower, queryLower) {
				fp := f.Path
				results = append(results, &SearchResult{
					Type:           "file",
					ID:             f.ID,
					Title:          f.Path,
					FilePath:       &fp,
					RepositoryID:   repo.ID,
					RepositoryName: repo.Name,
				})
			}
		}
	}

	return results, nil
}

// TraceabilityMatrix is the resolver for the traceabilityMatrix field.
func (r *queryResolver) TraceabilityMatrix(ctx context.Context, repositoryID string) (*TraceabilityMatrix, error) {
	if r.getStore(ctx) == nil {
		return &TraceabilityMatrix{
			Requirements: []*Requirement{},
			Symbols:      []*CodeSymbol{},
			Links:        []*RequirementLink{},
			Coverage:     0,
		}, nil
	}

	reqs, _ := r.getStore(ctx).GetRequirements(repositoryID, 10000, 0)
	links := r.getStore(ctx).GetLinksForRepo(repositoryID)

	// Build result
	var gqlReqs []*Requirement
	for _, req := range reqs {
		gqlReqs = append(gqlReqs, mapRequirement(req))
	}

	var gqlLinks []*RequirementLink
	symbolSet := make(map[string]bool)
	for _, l := range links {
		gqlLinks = append(gqlLinks, mapLink(l))
		symbolSet[l.SymbolID] = true
	}

	// Collect unique linked symbols
	var gqlSyms []*CodeSymbol
	syms, _ := r.getStore(ctx).GetSymbols(repositoryID, nil, nil, 10000, 0)
	for _, s := range syms {
		if symbolSet[s.ID] {
			gqlSyms = append(gqlSyms, mapSymbol(s))
		}
	}

	// Coverage = requirements with at least one link / total requirements
	linkedReqs := make(map[string]bool)
	for _, l := range links {
		linkedReqs[l.RequirementID] = true
	}
	coverage := 0.0
	if len(reqs) > 0 {
		coverage = float64(len(linkedReqs)) / float64(len(reqs))
	}

	if gqlReqs == nil {
		gqlReqs = []*Requirement{}
	}
	if gqlSyms == nil {
		gqlSyms = []*CodeSymbol{}
	}
	if gqlLinks == nil {
		gqlLinks = []*RequirementLink{}
	}

	return &TraceabilityMatrix{
		Requirements: gqlReqs,
		Symbols:      gqlSyms,
		Links:        gqlLinks,
		Coverage:     coverage,
	}, nil
}

// RequirementToCode is the resolver for the requirementToCode field.
func (r *queryResolver) RequirementToCode(ctx context.Context, requirementID string) ([]*RequirementLink, error) {
	if r.getStore(ctx) == nil {
		return []*RequirementLink{}, nil
	}
	links := r.getStore(ctx).GetLinksForRequirement(requirementID, false)
	var result []*RequirementLink
	for _, l := range links {
		result = append(result, mapLink(l))
	}
	if result == nil {
		result = []*RequirementLink{}
	}
	return result, nil
}

// CodeToRequirements is the resolver for the codeToRequirements field.
func (r *queryResolver) CodeToRequirements(ctx context.Context, symbolID string) ([]*RequirementLink, error) {
	if r.getStore(ctx) == nil {
		return []*RequirementLink{}, nil
	}
	links := r.getStore(ctx).GetLinksForSymbol(symbolID, false)
	var result []*RequirementLink
	for _, l := range links {
		result = append(result, mapLink(l))
	}
	if result == nil {
		result = []*RequirementLink{}
	}
	return result, nil
}

// SourceFile is the resolver for the sourceFile field.
func (r *queryResolver) SourceFile(ctx context.Context, repositoryID string, filePath string) (*SourceFileResult, error) {
	store := r.getStore(ctx)
	if store == nil {
		code := "STORE_UNAVAILABLE"
		message := "source storage is unavailable"
		return &SourceFileResult{Ok: false, ErrorCode: &code, Message: &message}, nil
	}

	repo := store.GetRepository(repositoryID)
	if repo == nil {
		code := "REPOSITORY_NOT_FOUND"
		message := "repository not found"
		return &SourceFileResult{Ok: false, ErrorCode: &code, Message: &message}, nil
	}

	repoRoot, err := resolveRepoSourcePath(repo)
	if err != nil {
		code := "SOURCE_UNAVAILABLE"
		message := err.Error()
		return &SourceFileResult{Ok: false, ErrorCode: &code, Message: &message}, nil
	}

	maxBytes := int64(1024 * 1024)
	if r.Config != nil && r.Config.Indexing.MaxFileSize > 0 {
		maxBytes = r.Config.Indexing.MaxFileSize
	}

	content, err := readSourceFileLimited(repoRoot, filePath, maxBytes)
	if err != nil {
		code := "SOURCE_READ_FAILED"
		message := err.Error()
		switch {
		case strings.Contains(err.Error(), "path traversal"):
			code = "INVALID_PATH"
			message = "invalid repository-relative path"
		case strings.Contains(err.Error(), "absolute path"):
			code = "INVALID_PATH"
			message = "absolute paths are not allowed"
		case strings.Contains(err.Error(), "exceeds max size"):
			code = "FILE_TOO_LARGE"
			message = fmt.Sprintf("file exceeds the %d byte source-view limit", maxBytes)
		case strings.Contains(err.Error(), "binary file"):
			code = "BINARY_FILE"
			message = "binary files are not supported in the source viewer"
		case strings.Contains(err.Error(), "no such file"), strings.Contains(err.Error(), "reading file info"):
			code = "FILE_NOT_FOUND"
			message = "file not found in repository source"
		}
		return &SourceFileResult{Ok: false, ErrorCode: &code, Message: &message}, nil
	}

	var fileMeta *graphstore.File
	for _, f := range store.GetFiles(repositoryID) {
		if f != nil && f.Path == filePath {
			fileMeta = f
			break
		}
	}

	lineCount := strings.Count(content, "\n")
	if content != "" {
		lineCount++
	}
	lang := LanguageUnknown
	if fileMeta != nil {
		if l := Language(strings.ToUpper(fileMeta.Language)); l.IsValid() {
			lang = l
		}
		if fileMeta.LineCount > 0 {
			lineCount = fileMeta.LineCount
		}
	} else {
		derived := strings.TrimPrefix(strings.TrimPrefix(deriveLanguage(filePath).String(), "LANGUAGE_"), "LANGUAGE")
		if l := Language(derived); l.IsValid() {
			lang = l
		}
	}

	var contentHash *string
	if fileMeta != nil && fileMeta.ContentHash != "" {
		contentHash = &fileMeta.ContentHash
	}

	return &SourceFileResult{
		Ok: true,
		File: &SourceFile{
			RepositoryID: repositoryID,
			FilePath:     filePath,
			Language:     lang,
			LineCount:    lineCount,
			Content:      content,
			ContentHash:  contentHash,
		},
	}, nil
}

// KnowledgeArtifacts is the resolver for the knowledgeArtifacts field.
func (r *queryResolver) KnowledgeArtifacts(ctx context.Context, repositoryID string, scopeType *KnowledgeScopeType, scopePath *string) ([]*KnowledgeArtifact, error) {
	if r.KnowledgeStore == nil {
		return []*KnowledgeArtifact{}, nil
	}
	artifacts := r.KnowledgeStore.GetKnowledgeArtifacts(repositoryID)
	if scopeType == nil && scopePath == nil {
		result := make([]*KnowledgeArtifact, len(artifacts))
		for i, a := range artifacts {
			result[i] = mapKnowledgeArtifact(a)
		}
		return result, nil
	}
	scope, err := artifactScopeFromInput(scopeType, scopePath)
	if err != nil {
		return nil, err
	}
	var result []*KnowledgeArtifact
	for _, a := range artifacts {
		artifactScope := knowledgepkg.ArtifactScope{ScopeType: knowledgepkg.ScopeRepository}
		if a.Scope != nil {
			artifactScope = a.Scope.Normalize()
		}
		if artifactScope.ScopeKey() == scope.ScopeKey() {
			result = append(result, mapKnowledgeArtifact(a))
		}
	}
	if result == nil {
		result = []*KnowledgeArtifact{}
	}
	return result, nil
}

// KnowledgeArtifact is the resolver for the knowledgeArtifact field.
func (r *queryResolver) KnowledgeArtifact(ctx context.Context, id string) (*KnowledgeArtifact, error) {
	if r.KnowledgeStore == nil {
		return nil, nil
	}
	a := r.KnowledgeStore.GetKnowledgeArtifact(id)
	if a == nil {
		return nil, nil
	}
	return mapKnowledgeArtifact(a), nil
}

// KnowledgeScopeChildren is the resolver for the knowledgeScopeChildren field.
func (r *queryResolver) KnowledgeScopeChildren(ctx context.Context, repositoryID string, scopeType KnowledgeScopeType, scopePath string, audience *KnowledgeAudience, depth *KnowledgeDepth) ([]*ScopeChild, error) {
	store := r.getStore(ctx)
	if store == nil {
		return []*ScopeChild{}, nil
	}
	if r.KnowledgeStore == nil {
		return []*ScopeChild{}, nil
	}
	scope := knowledgepkg.ArtifactScope{
		ScopeType: scopeTypeToGraph(scopeType),
		ScopePath: scopePath,
	}.Normalize()
	children := buildScopeChildren(store, repositoryID, scope)
	result := make([]*ScopeChild, 0, len(children))
	childAudience := knowledgeAudienceValue(audience)
	childDepth := knowledgeDepthValue(depth)
	for _, child := range children {
		key := knowledgepkg.ArtifactKey{
			RepositoryID: repositoryID,
			Type:         knowledgepkg.ArtifactCliffNotes,
			Audience:     childAudience,
			Depth:        childDepth,
			Scope:        child,
		}.Normalized()
		existing := r.KnowledgeStore.GetArtifactByKey(key)
		hasArtifact := existing != nil && existing.Status == knowledgepkg.StatusReady && !existing.Stale
		var summary *string
		if hasArtifact && len(existing.Sections) > 0 {
			if existing.Sections[0].Summary != "" {
				summary = &existing.Sections[0].Summary
			} else if existing.Sections[0].Content != "" {
				text := existing.Sections[0].Content
				if len(text) > 120 {
					text = text[:120] + "..."
				}
				summary = &text
			}
		}
		result = append(result, &ScopeChild{
			ScopeType:   mapScopeType(child.ScopeType),
			Label:       scopeLabel(child),
			ScopePath:   child.ScopePath,
			HasArtifact: hasArtifact,
			Summary:     summary,
		})
	}
	return result, nil
}

// ExecutionEntryPoints is the resolver for the executionEntryPoints field.
func (r *queryResolver) ExecutionEntryPoints(ctx context.Context, repositoryID string) ([]*ExecutionEntryPoint, error) {
	return r.executionEntryPoints(ctx, repositoryID)
}

// ExecutionPath is the resolver for the executionPath field.
func (r *queryResolver) ExecutionPath(ctx context.Context, input ExecutionPathInput) (*ExecutionPathResult, error) {
	return r.executionPath(ctx, input)
}

// AiGeneratedFiles is the resolver for the aiGeneratedFiles field.
func (r *queryResolver) AiGeneratedFiles(ctx context.Context, repositoryID string, minScore *float64) ([]*File, error) {
	store := r.getStore(ctx)
	if store == nil {
		return nil, fmt.Errorf("store not initialized")
	}

	threshold := 0.5
	if minScore != nil && *minScore > 0 {
		threshold = *minScore
	}

	allFiles := store.GetFiles(repositoryID)
	var result []*File
	for _, f := range allFiles {
		if f.AIScore >= threshold {
			result = append(result, mapFile(f))
		}
	}
	if result == nil {
		result = []*File{}
	}
	return result, nil
}

// UnderstandingScore is the resolver for the understandingScore field.
func (r *queryResolver) UnderstandingScore(ctx context.Context, repositoryID string) (*UnderstandingScore, error) {
	store := r.getStore(ctx)
	if store == nil {
		return nil, fmt.Errorf("store not initialized")
	}
	score := graphstore.ComputeUnderstandingScore(store, newKnowledgeFreshnessProvider(r.KnowledgeStore), repositoryID)
	return mapUnderstandingScore(score), nil
}

// LatestImpactReport is the resolver for the latestImpactReport field.
func (r *queryResolver) LatestImpactReport(ctx context.Context, repositoryID string) (*ImpactReport, error) {
	store := r.getStore(ctx)
	if store == nil {
		return nil, fmt.Errorf("store not initialized")
	}
	report := store.GetLatestImpactReport(repositoryID)
	if report == nil {
		return nil, nil
	}
	return mapImpactReport(report), nil
}

// ImpactReports is the resolver for the impactReports field.
func (r *queryResolver) ImpactReports(ctx context.Context, repositoryID string, limit *int) ([]*ImpactReport, error) {
	store := r.getStore(ctx)
	if store == nil {
		return nil, fmt.Errorf("store not initialized")
	}
	lim := 10
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	reports, _ := store.GetImpactReports(repositoryID, lim)
	result := make([]*ImpactReport, 0, len(reports))
	for _, rpt := range reports {
		result = append(result, mapImpactReport(rpt))
	}
	return result, nil
}

// LlmUsage is the resolver for the llmUsage field.
func (r *queryResolver) LlmUsage(ctx context.Context, repositoryID *string, limit *int) ([]*LLMUsageEntry, error) {
	panic(fmt.Errorf("not implemented: LlmUsage - llmUsage"))
}

// PlatformStats is the resolver for the platformStats field.
func (r *queryResolver) PlatformStats(ctx context.Context) (*PlatformStats, error) {
	if r.getStore(ctx) == nil {
		return &PlatformStats{}, nil
	}
	stats := r.getStore(ctx).Stats()

	// Sum LLM token usage
	usage := r.getStore(ctx).GetLLMUsage("", 0)
	totalIn, totalOut := 0, 0
	for _, u := range usage {
		totalIn += u.InputTokens
		totalOut += u.OutputTokens
	}

	return &PlatformStats{
		Repositories:      stats["repositories"],
		Files:             stats["files"],
		Symbols:           stats["symbols"],
		Requirements:      stats["requirements"],
		Links:             stats["links"],
		TotalInputTokens:  totalIn,
		TotalOutputTokens: totalOut,
	}, nil
}

// Files is the resolver for the files field.
func (r *repositoryResolver) Files(ctx context.Context, obj *Repository, limit *int, offset *int, path *string) (*FileConnection, error) {
	store := r.getStore(ctx)
	if store == nil {
		return &FileConnection{Nodes: []*File{}, TotalCount: 0}, nil
	}

	lim := 100
	off := 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}

	files, total := store.GetFilesPaginated(obj.ID, path, lim, off)
	nodes := make([]*File, 0, len(files))
	for _, f := range files {
		nodes = append(nodes, mapFile(f))
	}
	return &FileConnection{Nodes: nodes, TotalCount: total}, nil
}

// UnderstandingScore is the resolver for the understandingScore field.
func (r *repositoryResolver) UnderstandingScore(ctx context.Context, obj *Repository) (*UnderstandingScore, error) {
	store := r.getStore(ctx)
	if store == nil {
		return nil, nil
	}

	// Always compute the full score so sub-score breakdowns are populated.
	// The cache only stores the overall value, so using it would zero out
	// the breakdown fields (traceability, documentation, review, test, knowledge).
	score := graphstore.ComputeUnderstandingScore(store, newKnowledgeFreshnessProvider(r.KnowledgeStore), obj.ID)
	store.CacheUnderstandingScore(obj.ID, score.Overall)
	return mapUnderstandingScore(score), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Repository returns RepositoryResolver implementation.
func (r *Resolver) Repository() RepositoryResolver { return &repositoryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type repositoryResolver struct{ *Resolver }
