apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sourcebridge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sourcebridge/sourcebridge.git
    targetRevision: main
    path: deploy/kubernetes
    directory:
      exclude: 'kustomization.yaml'
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sourcebridge
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
