apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcebridge.fullname" . }}-api
  labels:
    {{- include "sourcebridge.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sourcebridge.api.selectorLabels" . | nindent 4 }}
