{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcebridge.fullname" . }}-redis
  labels:
    {{- include "sourcebridge.redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "sourcebridge.redis.selectorLabels" . | nindent 4 }}
{{- end }}
