apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcebridge.fullname" . }}-worker
  labels:
    {{- include "sourcebridge.worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sourcebridge.worker.selectorLabels" . | nindent 4 }}
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
