// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SourceBridge Contributors

// confluence_writer.go implements the Confluence storage-XHTML sink adapter
// (Workstream A1.P4).
//
// # Confluence storage format
//
// Confluence pages are stored as XHTML with two Atlassian custom namespaces:
//
//   - ac: — macros and structured content
//   - ri: — resource identifiers (page references, users, attachments)
//
// # Block ID preservation
//
// Each AST block is wrapped in a SourceBridge structured macro:
//
//	<ac:structured-macro ac:name="sourcebridge-block">
//	  <ac:parameter ac:name="id">b3f7a1...</ac:parameter>
//	  <ac:parameter ac:name="kind">paragraph</ac:parameter>
//	  <ac:parameter ac:name="owner">generated</ac:parameter>
//	  <ac:rich-text-body>
//	    <!-- rendered block content -->
//	  </ac:rich-text-body>
//	</ac:structured-macro>
//
// Confluence preserves custom macro parameters across view/edit/save cycles,
// so block IDs survive user edits to the surrounding content. The macro
// appears as a visible panel in the Confluence editor but does not clutter the
// published page — Confluence hides unknown macro bodies behind a collapsible
// "Unknown Macro" panel which still preserves the parameters.
//
// # Page reconciliation
//
// Pages are identified by the SourceBridge page ID stored as a page-level
// metadata property ("sourcebridge_page_id"). On upsert the writer:
//
//  1. Fetches the existing page (via ConfluenceClient).
//  2. Parses the block IDs and ownership from the macro parameters.
//  3. Runs block-level reconciliation ([ast.ReconcileBlocks]).
//  4. For generated blocks that changed, writes the new content.
//  5. Leaves human-edited blocks untouched.
//
// # Managed-page marker
//
// A Confluence info macro is emitted at the top of every managed page:
//
//	<ac:structured-macro ac:name="info">
//	  <ac:rich-text-body>
//	    This page is auto-generated by SourceBridge. …
//	  </ac:rich-text-body>
//	</ac:structured-macro>
//
// # Edit policy
//
// Default is local_to_sink (G.2). The caller is responsible for composing
// canonical + overlay[sink] via [ast.ComposeForSink] before passing the page
// to [ConfluenceWriter.WritePage].
//
// # Real HTTP client
//
// The [ConfluenceClient] interface is the port. Real HTTP implementations are
// out of scope for A1.P4. [MemoryConfluenceClient] is the in-memory fake used
// in tests and development.
package markdown

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"regexp"
	"strings"
	"sync"

	"github.com/sourcebridge/sourcebridge/internal/livingwiki/ast"
)

// ─────────────────────────────────────────────────────────────────────────────
// Inline markdown ↔ XHTML conversion
// ─────────────────────────────────────────────────────────────────────────────

// inlineMarkdownToXHTML converts the common inline markdown constructs in s to
// their Confluence XHTML equivalents.  It handles, in order:
//
//   - `code`           → <code>code</code>
//   - **bold** / __bold__  → <strong>bold</strong>
//   - *italic* / _italic_  → <em>italic</em>  (single delimiter, not inside words)
//   - [text](url)      → <a href="url">text</a>
//   - Bare URLs (http/https) → <a href="url">url</a>
//
// Citation handles of the form (path:start-end) are left unchanged; they are
// plain-text references whose link rendering is handled separately.
//
// The function escapes all literal text segments with xmlEscape before writing
// them so the output is valid XHTML.
func inlineMarkdownToXHTML(s string) string {
	var out strings.Builder
	inlineMarkdownToXHTMLInto(&out, s)
	return out.String()
}

// inlineMarkdownToXHTMLInto is the recursive implementation that writes into out.
// Splitting into a helper avoids allocating a builder for each recursive call.
func inlineMarkdownToXHTMLInto(out *strings.Builder, s string) {
	for len(s) > 0 {
		// Find the earliest of our recognised delimiters.
		type candidate struct {
			idx   int
			kind  string
		}
		best := candidate{idx: len(s) + 1}

		if i := strings.Index(s, "`"); i >= 0 && i < best.idx {
			best = candidate{i, "backtick"}
		}
		if i := strings.Index(s, "["); i >= 0 && i < best.idx {
			// Pre-validate: must look like [text](url) with a recognisable URL scheme.
			if _, _, _, valid := parseMdLinkAt(s, i); valid {
				best = candidate{i, "link"}
			}
		}
		if i, delim := findBoldDelimFrom(s, 0); i >= 0 && i < best.idx {
			_ = delim
			best = candidate{i, "bold"}
		}
		if i, _ := findItalicDelimFrom(s, 0); i >= 0 && i < best.idx {
			best = candidate{i, "italic"}
		}
		if i := findBareURL(s); i >= 0 && i < best.idx {
			best = candidate{i, "url"}
		}

		if best.idx > len(s) {
			// Nothing found — emit remainder as escaped text.
			out.WriteString(xmlEscape(s))
			return
		}

		// Flush literal text before the match.
		out.WriteString(xmlEscape(s[:best.idx]))
		s = s[best.idx:]

		switch best.kind {
		case "backtick":
			s = s[1:] // skip opening `
			end := strings.Index(s, "`")
			if end < 0 {
				out.WriteString("`")
				continue
			}
			out.WriteString("<code>")
			out.WriteString(xmlEscape(s[:end]))
			out.WriteString("</code>")
			s = s[end+1:]

		case "link":
			textStart, textEnd, urlEnd, _ := parseMdLinkAt(s, 0)
			textPart := s[textStart:textEnd]
			url := s[textEnd+2 : urlEnd] // s[textEnd+2:urlEnd] skips "]("
			if strings.HasPrefix(url, confluencePageScheme) {
				// Confluence cross-page link — emit <ac:link> macro.
				pageTitle := url[len(confluencePageScheme):]
				out.WriteString(`<ac:link>`)
				out.WriteString(`<ri:page ri:content-title="`)
				out.WriteString(xmlEscape(pageTitle))
				out.WriteString(`"/>`)
				out.WriteString(`<ac:link-body>`)
				out.WriteString(xmlEscape(textPart))
				out.WriteString(`</ac:link-body>`)
				out.WriteString(`</ac:link>`)
			} else {
				out.WriteString(`<a href="`)
				out.WriteString(xmlEscape(url))
				out.WriteString(`">`)
				out.WriteString(xmlEscape(textPart))
				out.WriteString("</a>")
			}
			s = s[urlEnd+1:] // skip past closing ')'

		case "bold":
			_, delim := findBoldDelimFrom(s, 0)
			s = s[len(delim):]
			end := strings.Index(s, delim)
			if end < 0 {
				out.WriteString(xmlEscape(delim))
				continue
			}
			out.WriteString("<strong>")
			out.WriteString(xmlEscape(s[:end]))
			out.WriteString("</strong>")
			s = s[end+len(delim):]

		case "italic":
			_, delim := findItalicDelimFrom(s, 0)
			s = s[len(delim):]
			end := strings.Index(s, delim)
			if end < 0 {
				out.WriteString(xmlEscape(delim))
				continue
			}
			out.WriteString("<em>")
			out.WriteString(xmlEscape(s[:end]))
			out.WriteString("</em>")
			s = s[end+len(delim):]

		case "url":
			end := bareURLEnd(s)
			url := s[:end]
			out.WriteString(`<a href="`)
			out.WriteString(xmlEscape(url))
			out.WriteString(`">`)
			out.WriteString(xmlEscape(url))
			out.WriteString("</a>")
			s = s[end:]
		}
	}
}

// confluencePageScheme is the URL scheme used to emit Confluence cross-page
// links. The portion after the scheme is treated as the target page's exact
// ri:content-title (no URL encoding). Example:
//
//	[Auth package](confluence-page:Architecture: internal/auth)
//	→ <ac:link><ri:page ri:content-title="Architecture: internal/auth"/>…</ac:link>
const confluencePageScheme = "confluence-page:"

// parseMdLinkAt parses a markdown link "[text](url)" that starts at s[at].
// Returns (textStart, textEnd, urlEnd, valid) where:
//
//	textStart = at+1 (byte after '[')
//	textEnd   = index of ']' in s
//	urlEnd    = index of ')' that closes the URL (the ')' char is at s[urlEnd])
//	valid     = true when the URL has a recognisable scheme
//
// Recognises http/https, relative paths, fragments, and the confluence-page:
// scheme (for cross-page Confluence links).
//
// On failure valid is false and the other values are meaningless.
func parseMdLinkAt(s string, at int) (textStart, textEnd, urlEnd int, valid bool) {
	if at >= len(s) || s[at] != '[' {
		return 0, 0, 0, false
	}
	closeText := strings.Index(s[at:], "](")
	if closeText < 0 {
		return 0, 0, 0, false
	}
	textEnd = at + closeText
	urlStart := textEnd + 2
	closeURL := strings.Index(s[urlStart:], ")")
	if closeURL < 0 {
		return 0, 0, 0, false
	}
	urlEnd = urlStart + closeURL
	url := s[urlStart:urlEnd]
	if !strings.HasPrefix(url, "http://") && !strings.HasPrefix(url, "https://") &&
		!strings.HasPrefix(url, "/") && !strings.HasPrefix(url, "#") &&
		!strings.HasPrefix(url, confluencePageScheme) {
		return 0, 0, 0, false
	}
	return at + 1, textEnd, urlEnd, true
}

// findBoldDelimFrom returns the index and delimiter string of the first "**" or
// "__" in s at or after position from.  Returns (-1,"") if none.
func findBoldDelimFrom(s string, from int) (int, string) {
	for _, delim := range []string{"**", "__"} {
		idx := strings.Index(s[from:], delim)
		if idx >= 0 {
			return from + idx, delim
		}
	}
	return -1, ""
}

// findItalicDelimFrom returns the index and delimiter of the first stand-alone
// '*' or '_' in s at or after position from.  A delimiter is considered
// stand-alone when it is not part of a bold delimiter ("**" / "__").
func findItalicDelimFrom(s string, from int) (int, string) {
	for i := from; i < len(s); i++ {
		switch s[i] {
		case '*':
			if i+1 < len(s) && s[i+1] == '*' {
				i++ // skip bold delimiter
				continue
			}
			return i, "*"
		case '_':
			if i+1 < len(s) && s[i+1] == '_' {
				i++
				continue
			}
			// Underscore in the middle of a word (e.g. snake_case) is not italic.
			if i > 0 && isWordChar(s[i-1]) {
				continue
			}
			return i, "_"
		}
	}
	return -1, ""
}

func isWordChar(b byte) bool {
	return (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9')
}

// findBareURL returns the index of the first "http://" or "https://" in s
// that is not immediately preceded by '"' or '(' (which would indicate it is
// already inside an href attribute or a markdown link).  Returns -1 if none.
func findBareURL(s string) int {
	best := -1
	for _, prefix := range []string{"https://", "http://"} {
		search := s
		offset := 0
		for {
			idx := strings.Index(search, prefix)
			if idx < 0 {
				break
			}
			abs := offset + idx
			// Skip URLs immediately preceded by '"' or '(' (href or md-link).
			if abs > 0 && (s[abs-1] == '"' || s[abs-1] == '(') {
				offset = abs + len(prefix)
				search = s[offset:]
				continue
			}
			if best < 0 || abs < best {
				best = abs
			}
			break
		}
	}
	return best
}

// bareURLEnd returns the index just past the end of a URL that starts at the
// beginning of s.  A URL ends at whitespace, '<', '>', '"', or ')'.
// Trailing sentence punctuation (.,;:!?) is also excluded when it is the last
// non-whitespace character before one of those terminators or end-of-string.
func bareURLEnd(s string) int {
	end := len(s)
	for i, r := range s {
		switch r {
		case ' ', '\t', '\n', '<', '>', '"', ')':
			end = i
			goto trim
		}
	}
trim:
	// Trim trailing punctuation that is unlikely to be part of the URL.
	for end > 0 {
		switch s[end-1] {
		case '.', ',', ';', ':', '!', '?':
			end--
		default:
			return end
		}
	}
	return end
}

// xhtmlInlineToMarkdown is the reverse of inlineMarkdownToXHTML: it converts
// common Confluence inline XHTML tags back to markdown syntax for round-trip
// stability.  It is intentionally simple: only the tags that inlineMarkdownToXHTML
// emits are handled.
func xhtmlInlineToMarkdown(s string) string {
	// <strong>…</strong> → **…**
	s = reStrong.ReplaceAllStringFunc(s, func(m string) string {
		inner := reStrong.FindStringSubmatch(m)
		if len(inner) < 2 {
			return m
		}
		return "**" + xmlUnescape(inner[1]) + "**"
	})
	// <em>…</em> → *…*
	s = reEm.ReplaceAllStringFunc(s, func(m string) string {
		inner := reEm.FindStringSubmatch(m)
		if len(inner) < 2 {
			return m
		}
		return "*" + xmlUnescape(inner[1]) + "*"
	})
	// <code>…</code> → `…`
	s = reCode.ReplaceAllStringFunc(s, func(m string) string {
		inner := reCode.FindStringSubmatch(m)
		if len(inner) < 2 {
			return m
		}
		return "`" + xmlUnescape(inner[1]) + "`"
	})
	// <a href="url">text</a> → [text](url)
	s = reAnchor.ReplaceAllStringFunc(s, func(m string) string {
		parts := reAnchor.FindStringSubmatch(m)
		if len(parts) < 3 {
			return m
		}
		url := xmlUnescape(parts[1])
		text := xmlUnescape(parts[2])
		return "[" + text + "](" + url + ")"
	})
	// Unescape remaining XML entities.
	return xmlUnescape(s)
}

var (
	reStrong = regexp.MustCompile(`(?s)<strong>(.*?)</strong>`)
	reEm     = regexp.MustCompile(`(?s)<em>(.*?)</em>`)
	reCode   = regexp.MustCompile(`(?s)<code>(.*?)</code>`)
	reAnchor = regexp.MustCompile(`(?s)<a href="([^"]*)">(.*?)</a>`)
)

// xmlUnescape reverses the five XML entity escapes applied by xmlEscape.
func xmlUnescape(s string) string {
	s = strings.ReplaceAll(s, "&amp;", "&")
	s = strings.ReplaceAll(s, "&lt;", "<")
	s = strings.ReplaceAll(s, "&gt;", ">")
	s = strings.ReplaceAll(s, "&quot;", `"`)
	s = strings.ReplaceAll(s, "&apos;", "'")
	return s
}

// ─────────────────────────────────────────────────────────────────────────────
// Port interface
// ─────────────────────────────────────────────────────────────────────────────

// ConfluenceProperties is a typed property bag attached to a Confluence page.
// SourceBridge uses it to store the sourcebridge_page_id and last-sync metadata.
type ConfluenceProperties map[string]string

// ConfluenceClient is the port interface for interacting with the Confluence
// REST API. Real implementations call the Confluence Cloud/Server REST API;
// [MemoryConfluenceClient] is the in-memory fake for tests.
//
// All methods receive a context so real implementations can respect
// cancellation and deadlines.
type ConfluenceClient interface {
	// GetPage fetches a page by its SourceBridge external ID.
	// Returns (xhtml, metadata, nil) when the page exists.
	// Returns (nil, nil, nil) when no page with externalID exists yet.
	GetPage(ctx context.Context, externalID string) (xhtml []byte, metadata ConfluenceProperties, err error)

	// UpsertPage creates or updates the page identified by externalID with the
	// given XHTML body and metadata properties. The implementation is
	// responsible for translating externalID to a Confluence page ID on update.
	UpsertPage(ctx context.Context, externalID string, xhtml []byte, metadata ConfluenceProperties) error

	// GetBlockByExternalID fetches the XHTML body of a specific block within a
	// page, identified by the block's SourceBridge block ID stored in the macro
	// parameter. Returns (xhtml, true, nil) when the block is found.
	// Returns (nil, false, nil) when the block does not exist in the page.
	GetBlockByExternalID(ctx context.Context, pageExternalID string, blockExternalID ast.BlockID) (xhtml []byte, ok bool, err error)

	// ListPagesByExternalIDPrefix returns the external IDs of all Confluence
	// pages whose sourcebridge_page_id property starts with prefix. Used by
	// the orphan-cleanup pass to find pages from a specific repo.
	// Implementations may return an empty slice rather than an error when the
	// capability is not available.
	ListPagesByExternalIDPrefix(ctx context.Context, prefix string) ([]string, error)

	// DeletePage permanently deletes the Confluence page identified by
	// externalID. Returns nil when the page did not exist (idempotent).
	DeletePage(ctx context.Context, externalID string) error

	// EnsurePage creates a stub page (typically a root or section page) if one
	// does not already exist with the given external ID, and returns the
	// Confluence numeric page ID either way.
	//
	// parentExternalID may be empty when the page should live at the space root.
	// When non-empty the parent page must already exist (caller's responsibility).
	// body is the initial XHTML body for new pages; existing pages are not updated.
	EnsurePage(ctx context.Context, externalID, title string, parentExternalID string, body []byte) (string, error)
}

// ─────────────────────────────────────────────────────────────────────────────
// In-memory fake
// ─────────────────────────────────────────────────────────────────────────────

// confluencePageRecord is the in-memory storage for one Confluence page.
type confluencePageRecord struct {
	xhtml      []byte
	properties ConfluenceProperties
}

// MemoryConfluenceClient is a thread-safe in-memory implementation of
// [ConfluenceClient] for use in tests and development.
type MemoryConfluenceClient struct {
	pages    map[string]*confluencePageRecord // externalID → record
	numericIDs map[string]string             // externalID → fake numeric Confluence page ID
	nextID   int
}

// NewMemoryConfluenceClient creates an empty [MemoryConfluenceClient].
func NewMemoryConfluenceClient() *MemoryConfluenceClient {
	return &MemoryConfluenceClient{
		pages:      make(map[string]*confluencePageRecord),
		numericIDs: make(map[string]string),
		nextID:     1000,
	}
}

// GetPage implements [ConfluenceClient].
func (m *MemoryConfluenceClient) GetPage(_ context.Context, externalID string) ([]byte, ConfluenceProperties, error) {
	rec, ok := m.pages[externalID]
	if !ok {
		return nil, nil, nil
	}
	// Return copies so callers can't mutate internal state.
	xhtml := make([]byte, len(rec.xhtml))
	copy(xhtml, rec.xhtml)
	props := make(ConfluenceProperties, len(rec.properties))
	for k, v := range rec.properties {
		props[k] = v
	}
	return xhtml, props, nil
}

// UpsertPage implements [ConfluenceClient].
func (m *MemoryConfluenceClient) UpsertPage(_ context.Context, externalID string, xhtml []byte, metadata ConfluenceProperties) error {
	body := make([]byte, len(xhtml))
	copy(body, xhtml)
	props := make(ConfluenceProperties, len(metadata))
	for k, v := range metadata {
		props[k] = v
	}
	m.pages[externalID] = &confluencePageRecord{xhtml: body, properties: props}
	return nil
}

// GetBlockByExternalID implements [ConfluenceClient] by parsing the stored
// XHTML to find the macro with the matching block ID parameter.
func (m *MemoryConfluenceClient) GetBlockByExternalID(_ context.Context, pageExternalID string, blockExternalID ast.BlockID) ([]byte, bool, error) {
	rec, ok := m.pages[pageExternalID]
	if !ok {
		return nil, false, nil
	}
	blocks := parseConfluenceBlocks(rec.xhtml)
	for _, b := range blocks {
		if b.id == blockExternalID {
			return []byte(b.rawXHTML), true, nil
		}
	}
	return nil, false, nil
}

// ListPagesByExternalIDPrefix implements [ConfluenceClient] by scanning the
// in-memory page map for keys with the given prefix.
func (m *MemoryConfluenceClient) ListPagesByExternalIDPrefix(_ context.Context, prefix string) ([]string, error) {
	var out []string
	for id := range m.pages {
		if strings.HasPrefix(id, prefix) {
			out = append(out, id)
		}
	}
	return out, nil
}

// DeletePage implements [ConfluenceClient] by removing the page from the
// in-memory map. Returns nil when the page does not exist (idempotent).
func (m *MemoryConfluenceClient) DeletePage(_ context.Context, externalID string) error {
	delete(m.pages, externalID)
	delete(m.numericIDs, externalID)
	return nil
}

// EnsurePage implements [ConfluenceClient]. It creates the page if it does not
// already exist, and returns a stable fake numeric Confluence page ID in both
// cases. Existing pages are left unchanged (the body argument is ignored for
// pre-existing pages).
func (m *MemoryConfluenceClient) EnsurePage(_ context.Context, externalID, title string, _ string, body []byte) (string, error) {
	if numID, ok := m.numericIDs[externalID]; ok {
		return numID, nil
	}
	// Create the page.
	cp := make([]byte, len(body))
	copy(cp, body)
	m.pages[externalID] = &confluencePageRecord{
		xhtml: cp,
		properties: ConfluenceProperties{
			"sourcebridge_page_id": externalID,
			propConfluenceTitle:    title,
		},
	}
	m.nextID++
	numID := fmt.Sprintf("%d", m.nextID)
	m.numericIDs[externalID] = numID
	return numID, nil
}

// NumericPageID returns the fake Confluence numeric page ID for the given
// external ID. Returns "" when the page does not exist. Used in tests.
func (m *MemoryConfluenceClient) NumericPageID(externalID string) string {
	return m.numericIDs[externalID]
}

// MutateBlock directly modifies the stored XHTML of a block, simulating a
// Confluence editor changing content. This is used in integration tests to
// inject "human edits" into the in-memory store without going through the
// normal WritePage path.
//
// newBodyXHTML is the XHTML content that replaces the block's rich-text body.
// The block's id, kind, and owner macro parameters are preserved.
func (m *MemoryConfluenceClient) MutateBlock(pageExternalID string, blockID ast.BlockID, newBodyXHTML string) error {
	rec, ok := m.pages[pageExternalID]
	if !ok {
		return fmt.Errorf("memory confluence: page %q not found", pageExternalID)
	}

	// Replace the rich-text body of the block identified by blockID.
	// We do a targeted string replacement of the macro content.
	xhtml := string(rec.xhtml)
	result, err := replaceBlockBody(xhtml, blockID, newBodyXHTML)
	if err != nil {
		return err
	}
	rec.xhtml = []byte(result)
	return nil
}

// replaceBlockBody replaces the body between sb-block open/close comment
// markers for the block whose id attribute matches blockID. Returns the
// modified XHTML or an error if the block is not found.
func replaceBlockBody(xhtml string, blockID ast.BlockID, newBodyXHTML string) (string, error) {
	escapedID := xmlEscape(string(blockID))

	// Locate every sb-block open comment and pick the one whose id attribute
	// matches blockID — attribute order in the comment is not guaranteed, so
	// we cannot match against a single literal substring.
	for _, loc := range reSBBlockOpen.FindAllStringSubmatchIndex(xhtml, -1) {
		attrSpan := xhtml[loc[2]:loc[3]]
		var matched bool
		for _, m := range reSBAttr.FindAllStringSubmatch(attrSpan, -1) {
			if m[1] == "id" && m[2] == escapedID {
				matched = true
				break
			}
		}
		if !matched {
			continue
		}

		openEnd := loc[1]
		closeRel := strings.Index(xhtml[openEnd:], sbBlockClosePrefix)
		if closeRel < 0 {
			break
		}
		closeAbs := openEnd + closeRel
		closeEnd := strings.Index(xhtml[closeAbs:], "-->")
		if closeEnd < 0 {
			break
		}
		closeEnd = closeAbs + closeEnd + len("-->")

		var b strings.Builder
		b.WriteString(xhtml[:openEnd])
		b.WriteString("\n")
		b.WriteString(strings.TrimSpace(newBodyXHTML))
		b.WriteString("\n")
		b.WriteString(sbBlockClose)
		b.WriteString(xhtml[closeEnd:])
		return b.String(), nil
	}

	return "", fmt.Errorf("confluence block %q not found in XHTML", blockID)
}

// extractAcParameter extracts the text content of <ac:parameter ac:name="name">…</ac:parameter>.
func extractAcParameter(xhtml, name string) string {
	pattern := fmt.Sprintf(`<ac:parameter ac:name="%s">`, xmlEscape(name))
	idx := strings.Index(xhtml, pattern)
	if idx < 0 {
		return ""
	}
	start := idx + len(pattern)
	end := strings.Index(xhtml[start:], "</ac:parameter>")
	if end < 0 {
		return ""
	}
	// Unescape the value.
	val := xhtml[start : start+end]
	val = strings.ReplaceAll(val, "&amp;", "&")
	val = strings.ReplaceAll(val, "&lt;", "<")
	val = strings.ReplaceAll(val, "&gt;", ">")
	val = strings.ReplaceAll(val, "&quot;", `"`)
	val = strings.ReplaceAll(val, "&apos;", "'")
	return val
}

// ─────────────────────────────────────────────────────────────────────────────
// ConfluenceWriterConfig
// ─────────────────────────────────────────────────────────────────────────────

// ConfluenceWriterConfig controls the behaviour of [ConfluenceWriter].
type ConfluenceWriterConfig struct {
	// SpaceKey is the Confluence space key (e.g. "ENGINEERING").
	// Used as a metadata property on upsert; not required for the in-memory fake.
	SpaceKey string

	// ParentPageID is the Confluence page ID of the parent page under which new
	// pages are created. Optional; if empty the page is created at the space root.
	ParentPageID string

	// RepoID is the SourceBridge repository ID. Used to construct stable
	// external IDs for the root and section pages.
	RepoID string

	// RepoName is the human-readable repository name. Used as the title of the
	// auto-generated "<RepoName> Living Wiki" root page.
	RepoName string
}

// hierarchyExternalIDs returns the stable external IDs for the root and
// Architecture section pages for this (writer, repo) combination.
func (c ConfluenceWriterConfig) hierarchyExternalIDs() (root, archSection string) {
	if c.RepoID == "" {
		return "", ""
	}
	return c.RepoID + ".__wiki_root__", c.RepoID + ".__section__.architecture"
}

// propParentExternalID is the per-call metadata key that overrides the
// default parent page (cfg.ParentPageID) when a page is first created.
// It is consumed by createPage and never written as a Confluence content-property.
const propParentExternalID = "sb_parent_external_id"

// ─────────────────────────────────────────────────────────────────────────────
// ConfluenceWriter
// ─────────────────────────────────────────────────────────────────────────────

// ConfluenceWriter is the Confluence storage-XHTML sink adapter.
//
// Call [WritePage] to do the full read-diff-write cycle:
//  1. Ensure the root and Architecture section pages exist (once per writer lifetime).
//  2. Fetch the existing Confluence page via the [ConfluenceClient].
//  3. Parse the existing XHTML to recover block IDs and ownership.
//  4. Run block-level reconciliation.
//  5. Write only changed generated blocks; preserve human-edited blocks.
//  6. Upsert the composed XHTML via the [ConfluenceClient].
//
// The caller must compose canonical + overlay[sink] via [ast.ComposeForSink]
// before calling WritePage when the sink has a local_to_sink policy.
type ConfluenceWriter struct {
	client ConfluenceClient
	cfg    ConfluenceWriterConfig

	// hierarchyOnce guards the one-time creation of the root and Architecture
	// section pages. Concurrent WritePage calls will all block until the first
	// caller has created the pages; subsequent callers proceed immediately.
	hierarchyOnce sync.Once
	hierarchyErr  error // non-nil when EnsurePage calls fail during setup
}

// NewConfluenceWriter creates a [ConfluenceWriter] using the given client.
func NewConfluenceWriter(client ConfluenceClient, cfg ConfluenceWriterConfig) *ConfluenceWriter {
	return &ConfluenceWriter{client: client, cfg: cfg}
}

// ensureHierarchy creates the root and Architecture section pages exactly once
// per writer lifetime. It is called from WritePage under a sync.Once so
// concurrent page writes block until the hierarchy exists.
//
// When cfg.RepoID is empty the hierarchy is disabled and this is a no-op.
func (cw *ConfluenceWriter) ensureHierarchy(ctx context.Context) error {
	cw.hierarchyOnce.Do(func() {
		rootID, archID := cw.cfg.hierarchyExternalIDs()
		if rootID == "" {
			return // hierarchy disabled (no RepoID configured)
		}

		repoName := cw.cfg.RepoName
		if repoName == "" {
			repoName = cw.cfg.RepoID
		}

		rootBody := fmt.Appendf(nil,
			`<p>This is the auto-generated SourceBridge wiki for %s. Pages are kept in sync as the codebase evolves.</p>`+"\n"+
				`<ac:structured-macro ac:name="children" />`,
			xmlEscape(repoName),
		)

		// Root page lives at the configured space root (no parent external ID).
		_, err := cw.client.EnsurePage(ctx, rootID, repoName+" Living Wiki", "", rootBody)
		if err != nil {
			cw.hierarchyErr = fmt.Errorf("confluence_writer: ensure root page: %w", err)
			return
		}

		archBody := fmt.Appendf(nil,
			`<p>Architecture documentation for %s.</p>`+"\n"+
				`<ac:structured-macro ac:name="children" />`,
			xmlEscape(repoName),
		)

		// Architecture section is parented to the root.
		_, err = cw.client.EnsurePage(ctx, archID, "Architecture", rootID, archBody)
		if err != nil {
			cw.hierarchyErr = fmt.Errorf("confluence_writer: ensure architecture section: %w", err)
		}
	})
	return cw.hierarchyErr
}

// parentExternalIDForPage determines which parent page a new content page
// should be created under, expressed as a SourceBridge external ID.
//
// Routing rules (v1):
//   - Pages whose ID matches <repoID>.arch.* → Architecture section
//   - All other pages → root page
//
// Returns "" when hierarchy is disabled (no RepoID configured).
func (cw *ConfluenceWriter) parentExternalIDForPage(pageID string) string {
	rootID, archID := cw.cfg.hierarchyExternalIDs()
	if rootID == "" {
		return ""
	}
	prefix := cw.cfg.RepoID + ".arch."
	if strings.HasPrefix(pageID, prefix) {
		return archID
	}
	return rootID
}

// WritePage performs the read-diff-write cycle for one page.
//
// The incoming page's blocks are expected to carry stable IDs already
// assigned by the orchestrator (canonical AST or proposed AST).
//
// Algorithm:
//  1. Ensure root and Architecture section pages exist (once per writer lifetime).
//  2. Fetch the existing Confluence page.
//  3. Parse existing blocks to build a map of blockID → existing block.
//  4. For each incoming block:
//     - If an existing block with the same ID is human-edited or human-only,
//       preserve its content and owner (the human edit wins).
//     - Otherwise use the incoming block's content.
//  5. Render and upsert, injecting the per-page parent external ID so new pages
//     land under the correct section rather than the space root.
//
// Caller responsibility: pass in the result of [ast.ComposeForSink] when the
// Confluence sink has a local_to_sink overlay, so that per-sink divergent
// content is included in the write.
func (cw *ConfluenceWriter) WritePage(ctx context.Context, page ast.Page) error {
	// Step 1: Ensure hierarchy pages exist (idempotent, runs once per writer).
	if err := cw.ensureHierarchy(ctx); err != nil {
		return err
	}

	// Step 2: Fetch existing page.
	existingXHTML, _, err := cw.client.GetPage(ctx, page.ID)
	if err != nil {
		return fmt.Errorf("confluence_writer: GetPage %q: %w", page.ID, err)
	}

	// Step 3: Parse existing blocks to recover ownership by block ID.
	existingByID := make(map[ast.BlockID]ast.Block)
	if len(existingXHTML) > 0 {
		for _, b := range confluenceXHTMLToBlocks(existingXHTML) {
			existingByID[b.ID] = b
		}
	}

	// Step 4: Compose the output blocks, preserving human-edited content.
	output := make([]ast.Block, len(page.Blocks))
	for i, blk := range page.Blocks {
		output[i] = blk
		if existing, ok := existingByID[blk.ID]; ok {
			if existing.Owner == ast.OwnerHumanEdited || existing.Owner == ast.OwnerHumanOnly {
				// Human edit wins — preserve the existing content and owner.
				output[i].Content = existing.Content
				output[i].Owner = existing.Owner
			}
		}
	}

	// Step 5: Render to XHTML and upsert.
	var buf bytes.Buffer
	if err := writeConfluencePage(&buf, ast.Page{
		ID:         page.ID,
		Manifest:   page.Manifest,
		Blocks:     output,
		Provenance: page.Provenance,
	}); err != nil {
		return fmt.Errorf("confluence_writer: render %q: %w", page.ID, err)
	}

	props := ConfluenceProperties{
		"sourcebridge_page_id": page.ID,
		"space_key":            cw.cfg.SpaceKey,
		// Title is consumed by the HTTP client when creating/updating the
		// Confluence page. Sinks that don't read this property (e.g. the
		// in-memory fake) just store it. We prefer the page's first heading
		// because that's the text humans authored as the natural title;
		// otherwise fall back to a deterministic humanization of the page ID.
		propConfluenceTitle: deriveConfluenceTitle(page),
	}

	// Inject the per-page parent so new pages land under the correct section
	// rather than the configured top-level parentPageID. The HTTP client reads
	// this and resolves it to a Confluence numeric ID before the CREATE call.
	if parentExtID := cw.parentExternalIDForPage(page.ID); parentExtID != "" {
		props[propParentExternalID] = parentExtID
	}

	if err := cw.client.UpsertPage(ctx, page.ID, buf.Bytes(), props); err != nil {
		return fmt.Errorf("confluence_writer: UpsertPage %q: %w", page.ID, err)
	}

	return nil
}

// propConfluenceTitle is the property key on UpsertPage's metadata that the
// HTTP client uses as the Confluence page title. It is not persisted as a
// Confluence content-property — the HTTP layer pulls it out before the
// remaining keys are written through to Confluence.
const propConfluenceTitle = "sb_confluence_title"

// deriveConfluenceTitle returns the page's Confluence title as a deterministic
// humanization of page.ID via HumanizePageID. Using a stable ID-derived title
// (rather than the first heading) ensures cross-page links always resolve —
// a heading can be edited by a human but the page ID never changes.
func deriveConfluenceTitle(page ast.Page) string {
	return HumanizePageID(page.ID)
}

// HumanizePageID converts a SourceBridge page ID into a human-friendly title.
// The transformation is deterministic so create-time and search-time produce
// the same string, which is required for cross-page <ac:link> resolution.
//
// Special cases (matched after stripping a leading UUID repo-id segment):
//   - "arch.<rest>" → "Architecture: <rest with . replaced by />"
//   - "system_overview" → "System Overview"
//   - "glossary" → "Glossary"
//   - "api_reference" → "API Reference"
//   - Other single-segment IDs → title-case, underscore→space, common acronyms uppercased
//   - Multi-segment IDs → join with " · ", each segment title-cased
func HumanizePageID(externalID string) string {
	if externalID == "" {
		return externalID
	}
	parts := strings.Split(externalID, ".")
	// Drop a leading repo-id segment when it looks like a UUID (contains 4
	// hyphens) — repo IDs would otherwise dominate the visible title.
	if len(parts) > 1 && strings.Count(parts[0], "-") == 4 {
		parts = parts[1:]
	}
	if len(parts) == 0 {
		return externalID
	}

	// Special case: arch.* → "Architecture: <path with / separators>"
	if parts[0] == "arch" && len(parts) > 1 {
		rest := strings.Join(parts[1:], "/")
		return "Architecture: " + rest
	}

	// Special case: well-known single-segment IDs.
	if len(parts) == 1 {
		switch parts[0] {
		case "system_overview":
			return "System Overview"
		case "glossary":
			return "Glossary"
		case "api_reference":
			return "API Reference"
		}
	}

	// General: title-case each segment with acronym uppercasing.
	pretty := make([]string, 0, len(parts))
	for _, p := range parts {
		pretty = append(pretty, humanizeSegment(p))
	}
	return strings.Join(pretty, " · ")
}

// humanizeSegment converts a single page-ID segment (e.g. "api_reference")
// to a human-friendly label ("API Reference"). It:
//  1. Replaces underscores with spaces.
//  2. Uppercases each word if it is a known acronym; otherwise title-cases it.
func humanizeSegment(s string) string {
	words := strings.Fields(strings.ReplaceAll(s, "_", " "))
	for i, w := range words {
		if isAcronym(strings.ToLower(w)) {
			words[i] = strings.ToUpper(w)
		} else if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

// isAcronym returns true when w (already lowercased) is a well-known acronym
// that should be rendered in full uppercase.
func isAcronym(w string) bool {
	switch w {
	case "api", "db", "id", "url", "http", "sql", "xml", "json",
		"yaml", "aws", "gcp", "dns", "tls", "ui", "iam", "rpc",
		"grpc", "jwt", "oauth", "oidc", "ci", "cd", "sdk", "cli",
		"abi", "arn", "sqs", "sns", "s3", "ec2", "vpc":
		return true
	}
	return false
}

// WriteXHTML renders page to Confluence storage XHTML without performing
// read-diff-write reconciliation. Useful for testing the rendering output
// independently of the full WritePage cycle.
func WriteXHTML(w io.Writer, page ast.Page) error {
	return writeConfluencePage(w, page)
}

// ─────────────────────────────────────────────────────────────────────────────
// XHTML rendering
// ─────────────────────────────────────────────────────────────────────────────

// managedPageMarkerXHTML is the info macro emitted at the top of every
// SourceBridge-managed Confluence page.
const managedPageMarkerXHTML = `<ac:structured-macro ac:name="info">
<ac:rich-text-body>
<p>This page is auto-generated by SourceBridge. Edits made directly may be overwritten unless this block is human-edited.</p>
</ac:rich-text-body>
</ac:structured-macro>
`

// writeConfluencePage renders the full page XHTML including the managed marker.
func writeConfluencePage(w io.Writer, page ast.Page) error {
	// Managed-page marker.
	if _, err := io.WriteString(w, managedPageMarkerXHTML); err != nil {
		return err
	}

	for _, blk := range page.Blocks {
		if err := writeConfluenceBlock(w, blk); err != nil {
			return fmt.Errorf("confluence block %q: %w", blk.ID, err)
		}
	}
	return nil
}

// sb-block round-trip markers. These are HTML comments rather than a custom
// Confluence macro, so the page renders correctly in any Confluence instance
// (no app/macro install required) while still letting the reconciler recover
// per-block ownership on the next write.
//
// Format:
//
//	<!-- sb:block id="..." kind="..." owner="..." -->
//	<plain XHTML for the block>
//	<!-- /sb:block -->
const (
	sbBlockOpenPrefix = "<!-- sb:block"
	sbBlockClosePrefix = "<!-- /sb:block"
	sbBlockClose      = "<!-- /sb:block -->"
)

// writeConfluenceBlock renders one block surrounded by sb-block HTML-comment
// markers and the block's plain XHTML body.
func writeConfluenceBlock(w io.Writer, blk ast.Block) error {
	openComment := fmt.Sprintf(`<!-- sb:block id=%q kind=%q owner=%q -->`,
		xmlEscape(string(blk.ID)),
		xmlEscape(string(blk.Kind)),
		xmlEscape(string(blk.Owner)),
	)
	if _, err := fmt.Fprintln(w, openComment); err != nil {
		return err
	}
	if err := writeConfluenceBlockContent(w, blk.Kind, blk.Content); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, sbBlockClose); err != nil {
		return err
	}
	return nil
}

// writeConfluenceBlockContent renders one block's content as Confluence XHTML.
func writeConfluenceBlockContent(w io.Writer, kind ast.BlockKind, content ast.BlockContent) error {
	switch kind {
	case ast.BlockKindHeading:
		return writeConfluenceHeading(w, content)
	case ast.BlockKindParagraph:
		return writeConfluenceParagraph(w, content)
	case ast.BlockKindCode:
		return writeConfluenceCode(w, content)
	case ast.BlockKindTable:
		return writeConfluenceTable(w, content)
	case ast.BlockKindCallout:
		return writeConfluenceCallout(w, content)
	case ast.BlockKindEmbed:
		return writeConfluenceEmbed(w, content)
	case ast.BlockKindFreeform:
		return writeConfluenceFreeform(w, content)
	case ast.BlockKindStaleBanner:
		return writeConfluenceStaleBanner(w, content)
	default:
		// Unknown kind — wrap as paragraph so the page doesn't break.
		if _, err := fmt.Fprintf(w, "<p>[unknown block kind: %s]</p>\n", xmlEscape(string(kind))); err != nil {
			return err
		}
		return nil
	}
}

func writeConfluenceHeading(w io.Writer, content ast.BlockContent) error {
	if content.Heading == nil {
		return nil
	}
	tag := headingTagForLevel(content.Heading.Level)
	if err := writeOpenTag(w, tag); err != nil {
		return err
	}
	if err := writeText(w, content.Heading.Text); err != nil {
		return err
	}
	if err := writeCloseTag(w, tag); err != nil {
		return err
	}
	return writeln(w)
}

func writeConfluenceParagraph(w io.Writer, content ast.BlockContent) error {
	if content.Paragraph == nil {
		return nil
	}
	// Convert inline markdown constructs to Confluence XHTML inline tags so
	// Confluence renders them correctly (bold, italic, code, links).
	// Citation handles (path:start-end) are left as-is.
	if err := writeOpenTag(w, "p"); err != nil {
		return err
	}
	xhtml := inlineMarkdownToXHTML(content.Paragraph.Markdown)
	if _, err := fmt.Fprint(w, xhtml); err != nil {
		return err
	}
	if err := writeCloseTag(w, "p"); err != nil {
		return err
	}
	return writeln(w)
}

func writeConfluenceCode(w io.Writer, content ast.BlockContent) error {
	if content.Code == nil {
		return nil
	}
	// Confluence Code Block macro.
	if err := writeAcMacroOpen(w, "code"); err != nil {
		return err
	}
	lang := confluenceCodeLanguage(content.Code.Language)
	if err := writeAcParameter(w, "language", lang); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	// Code body goes in a plain-text body (not rich-text).
	if err := writeOpenTag(w, "ac:plain-text-body"); err != nil {
		return err
	}
	// CDATA wraps code to prevent XML special-character escaping.
	if _, err := fmt.Fprintf(w, "<![CDATA[%s]]>", content.Code.Body); err != nil {
		return err
	}
	if err := writeCloseTag(w, "ac:plain-text-body"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	return writeAcMacroClose(w)
}

func writeConfluenceTable(w io.Writer, content ast.BlockContent) error {
	if content.Table == nil {
		return nil
	}
	t := content.Table
	if len(t.Headers) == 0 {
		return nil
	}

	if err := writeOpenTag(w, "table"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}

	// Header row.
	if err := writeOpenTag(w, "tr"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	for _, h := range t.Headers {
		if err := writeOpenTag(w, "th"); err != nil {
			return err
		}
		if err := writeText(w, h); err != nil {
			return err
		}
		if err := writeCloseTag(w, "th"); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}
	if err := writeCloseTag(w, "tr"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}

	// Data rows.
	for _, row := range t.Rows {
		if err := writeOpenTag(w, "tr"); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
		for _, cell := range row {
			if err := writeOpenTag(w, "td"); err != nil {
				return err
			}
			if err := writeText(w, cell); err != nil {
				return err
			}
			if err := writeCloseTag(w, "td"); err != nil {
				return err
			}
			if _, err := fmt.Fprintln(w); err != nil {
				return err
			}
		}
		if err := writeCloseTag(w, "tr"); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}

	if err := writeCloseTag(w, "table"); err != nil {
		return err
	}
	return writeln(w)
}

func writeConfluenceCallout(w io.Writer, content ast.BlockContent) error {
	if content.Callout == nil {
		return nil
	}
	// Map callout kind to Confluence macro name.
	macroName := calloutKindToConfluenceMacro(content.Callout.Kind)
	if err := writeAcMacroOpen(w, macroName); err != nil {
		return err
	}
	if err := writeAcRichTextBodyWrap(w, func(inner io.Writer) error {
		if err := writeOpenTag(inner, "p"); err != nil {
			return err
		}
		if err := writeText(inner, content.Callout.Body); err != nil {
			return err
		}
		if err := writeCloseTag(inner, "p"); err != nil {
			return err
		}
		return writeln(inner)
	}); err != nil {
		return err
	}
	return writeAcMacroClose(w)
}

// calloutKindToConfluenceMacro maps callout kind strings to Confluence macro names.
// Confluence has: note, tip, info, warning.
func calloutKindToConfluenceMacro(kind string) string {
	switch strings.ToLower(kind) {
	case "warning", "danger":
		return "warning"
	case "tip":
		return "tip"
	case "note":
		return "note"
	default:
		return "info"
	}
}

func writeConfluenceEmbed(w io.Writer, content ast.BlockContent) error {
	if content.Embed == nil {
		return nil
	}
	// Embeds are represented as a Confluence page include macro.
	if err := writeAcMacroOpen(w, "include"); err != nil {
		return err
	}
	if err := writeOpenTag(w, "ri:page", "ri:content-title", content.Embed.TargetPageID); err != nil {
		return err
	}
	if err := writeCloseTag(w, "ri:page"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w); err != nil {
		return err
	}
	if content.Embed.TargetBlockID != "" {
		if err := writeAcParameter(w, "block_id", string(content.Embed.TargetBlockID)); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}
	return writeAcMacroClose(w)
}

func writeConfluenceFreeform(w io.Writer, content ast.BlockContent) error {
	if content.Freeform == nil {
		return nil
	}
	// Freeform content is stored as raw text inside a paragraph. Callers
	// writing freeform blocks are responsible for ensuring the raw content is
	// valid XHTML — we do not escape it here.
	if _, err := fmt.Fprintln(w, content.Freeform.Raw); err != nil {
		return err
	}
	return nil
}

func writeConfluenceStaleBanner(w io.Writer, content ast.BlockContent) error {
	if content.StaleBanner == nil {
		return nil
	}
	s := content.StaleBanner
	// Stale banners render as Confluence warning macros.
	if err := writeAcMacroOpen(w, "warning"); err != nil {
		return err
	}
	if err := writeAcRichTextBodyWrap(w, func(inner io.Writer) error {
		if err := writeOpenTag(inner, "p"); err != nil {
			return err
		}
		syms := strings.Join(s.TriggeringSymbols, ", ")
		text := fmt.Sprintf("This page may be out of date. Recent changes to %s (commit %s) may affect this content.", syms, s.TriggeringCommit)
		if s.RefreshURL != "" {
			text += " Refresh from source: " + s.RefreshURL
		}
		if s.NextRegenWindow != "" {
			text += " Next scheduled regen: " + s.NextRegenWindow
		}
		if err := writeText(inner, text); err != nil {
			return err
		}
		if err := writeCloseTag(inner, "p"); err != nil {
			return err
		}
		return writeln(inner)
	}); err != nil {
		return err
	}
	return writeAcMacroClose(w)
}

// ─────────────────────────────────────────────────────────────────────────────
// XHTML → AST parsing (for reconciliation read-back)
// ─────────────────────────────────────────────────────────────────────────────

// confluenceParsedBlock is the result of parsing one sourcebridge-block macro
// from stored Confluence XHTML.
type confluenceParsedBlock struct {
	id      ast.BlockID
	kind    ast.BlockKind
	owner   ast.Owner
	rawXHTML string
}

// reSBBlockOpen matches the sb-block open comment and captures id/kind/owner
// in any order. The attribute regexes use \s+ separators so additional
// attributes can be added later without breaking back-compat.
var reSBBlockOpen = regexp.MustCompile(`<!--\s*sb:block\s+([^>]*?)\s*-->`)
var reSBAttr = regexp.MustCompile(`(\w+)\s*=\s*"([^"]*)"`)

// parseConfluenceBlocks extracts every sb-block-marked region from XHTML and
// returns the block metadata plus the raw body that lived between the
// open/close markers.
func parseConfluenceBlocks(xhtml []byte) []confluenceParsedBlock {
	s := string(xhtml)
	var results []confluenceParsedBlock

	offset := 0
	for offset < len(s) {
		loc := reSBBlockOpen.FindStringSubmatchIndex(s[offset:])
		if loc == nil {
			break
		}
		// loc[0:1] is the full open comment span within s[offset:].
		openStart := offset + loc[0]
		openEnd := offset + loc[1]
		attrSpan := s[offset+loc[2] : offset+loc[3]]

		// Locate the matching close marker. We accept "<!-- /sb:block -->" and
		// any whitespace-flexible variant so trivial editor reformats survive.
		closeRel := strings.Index(s[openEnd:], sbBlockClosePrefix)
		if closeRel < 0 {
			break
		}
		// Find the actual end-of-comment past the close prefix.
		closeAbs := openEnd + closeRel
		closeEnd := strings.Index(s[closeAbs:], "-->")
		if closeEnd < 0 {
			break
		}
		closeEnd = closeAbs + closeEnd + len("-->")

		body := strings.TrimSpace(s[openEnd:closeAbs])

		var id, kind, owner string
		for _, m := range reSBAttr.FindAllStringSubmatch(attrSpan, -1) {
			switch m[1] {
			case "id":
				id = m[2]
			case "kind":
				kind = m[2]
			case "owner":
				owner = m[2]
			}
		}

		if id != "" {
			results = append(results, confluenceParsedBlock{
				id:      ast.BlockID(id),
				kind:    ast.BlockKind(kind),
				owner:   ast.Owner(owner),
				rawXHTML: body,
			})
		}

		_ = openStart
		offset = closeEnd
	}
	return results
}

// confluenceXHTMLToBlocks converts parsed Confluence block data to [ast.Block]
// values. Content fields are partially reconstructed from XHTML; for
// reconciliation purposes, we need at minimum the ID, Kind, and Owner so that
// human-edited blocks are recognised and preserved.
func confluenceXHTMLToBlocks(xhtml []byte) []ast.Block {
	parsed := parseConfluenceBlocks(xhtml)
	blocks := make([]ast.Block, 0, len(parsed))
	for _, p := range parsed {
		blk := ast.Block{
			ID:    p.id,
			Kind:  p.kind,
			Owner: p.owner,
		}
		// Reconstruct content from XHTML for fingerprinting.
		blk.Content = confluenceXHTMLToBlockContent(p.kind, p.rawXHTML)
		blocks = append(blocks, blk)
	}
	return blocks
}

// confluenceXHTMLToBlockContent does a best-effort reconstruction of block
// content from Confluence XHTML. Heading, paragraph, and code are recovered
// with reasonable fidelity; table and callout are partial. The primary use
// case is content-fingerprint matching during reconciliation, not perfect
// round-trip.
func confluenceXHTMLToBlockContent(kind ast.BlockKind, rawXHTML string) ast.BlockContent {
	switch kind {
	case ast.BlockKindHeading:
		return confluenceParseHeading(rawXHTML)
	case ast.BlockKindParagraph:
		return confluenceParseParagraph(rawXHTML)
	case ast.BlockKindCode:
		return confluenceParseCode(rawXHTML)
	case ast.BlockKindTable:
		return confluenceParseTable(rawXHTML)
	case ast.BlockKindCallout:
		return confluenceParseCallout(rawXHTML)
	case ast.BlockKindStaleBanner:
		return confluenceParseStaleBanner(rawXHTML)
	case ast.BlockKindFreeform:
		return ast.BlockContent{
			Freeform: &ast.FreeformContent{Raw: strings.TrimSpace(rawXHTML)},
		}
	default:
		return ast.BlockContent{
			Freeform: &ast.FreeformContent{Raw: strings.TrimSpace(rawXHTML)},
		}
	}
}

// reHeadingTag matches an opening heading tag and captures the level digit and content.
// Go's regexp does not support backreferences, so we match the open/close tags separately.
var reHeadingTag = regexp.MustCompile(`(?i)<(h[1-6])[^>]*>`)

func confluenceParseHeading(rawXHTML string) ast.BlockContent {
	m := reHeadingTag.FindStringSubmatch(rawXHTML)
	if m == nil {
		return ast.BlockContent{
			Heading: &ast.HeadingContent{Level: 1, Text: strings.TrimSpace(stripTags(rawXHTML))},
		}
	}
	tag := strings.ToLower(m[1])
	level := 1
	if len(tag) == 2 && tag[0] == 'h' {
		level = int(tag[1] - '0')
	}
	// Strip the opening tag, content between tags, closing tag.
	closeTag := "</" + tag + ">"
	text := rawXHTML
	if start := strings.Index(text, m[0]); start >= 0 {
		text = text[start+len(m[0]):]
	}
	if end := strings.Index(strings.ToLower(text), closeTag); end >= 0 {
		text = text[:end]
	}
	return ast.BlockContent{
		Heading: &ast.HeadingContent{Level: level, Text: strings.TrimSpace(stripTags(text))},
	}
}

func confluenceParseParagraph(rawXHTML string) ast.BlockContent {
	// Strip the outer <p>…</p> wrapper if present.
	inner := rawXHTML
	if i := strings.Index(inner, "<p>"); i >= 0 {
		inner = inner[i+3:]
		if j := strings.LastIndex(inner, "</p>"); j >= 0 {
			inner = inner[:j]
		}
	}
	// Reverse the inline XHTML tags back to markdown syntax.
	text := xhtmlInlineToMarkdown(strings.TrimSpace(inner))
	return ast.BlockContent{
		Paragraph: &ast.ParagraphContent{Markdown: text},
	}
}

func confluenceParseCode(rawXHTML string) ast.BlockContent {
	// Extract language from ac:parameter and body from CDATA.
	lang := extractAcParameter(rawXHTML, "language")
	body := extractCDATA(rawXHTML)
	return ast.BlockContent{
		Code: &ast.CodeContent{Language: lang, Body: body},
	}
}

// reConfluenceTable parses table cells out of simple Confluence XHTML tables.
var reTH = regexp.MustCompile(`(?i)<th[^>]*>([\s\S]*?)</th>`)
var reTD = regexp.MustCompile(`(?i)<td[^>]*>([\s\S]*?)</td>`)
var reTR = regexp.MustCompile(`(?i)<tr[^>]*>([\s\S]*?)</tr>`)

func confluenceParseTable(rawXHTML string) ast.BlockContent {
	var headers []string
	var rows [][]string

	trMatches := reTR.FindAllStringSubmatch(rawXHTML, -1)
	for i, trm := range trMatches {
		rowXHTML := trm[1]
		if i == 0 {
			// Header row — th elements.
			for _, thm := range reTH.FindAllStringSubmatch(rowXHTML, -1) {
				headers = append(headers, strings.TrimSpace(stripTags(thm[1])))
			}
			if len(headers) == 0 {
				// Headerless table — treat first tr as data.
				for _, tdm := range reTD.FindAllStringSubmatch(rowXHTML, -1) {
					headers = append(headers, strings.TrimSpace(stripTags(tdm[1])))
				}
			}
		} else {
			var row []string
			for _, tdm := range reTD.FindAllStringSubmatch(rowXHTML, -1) {
				row = append(row, strings.TrimSpace(stripTags(tdm[1])))
			}
			if len(row) > 0 {
				rows = append(rows, row)
			}
		}
	}

	return ast.BlockContent{
		Table: &ast.TableContent{Headers: headers, Rows: rows},
	}
}

func confluenceParseCallout(rawXHTML string) ast.BlockContent {
	text := strings.TrimSpace(stripTags(rawXHTML))
	return ast.BlockContent{
		Callout: &ast.CalloutContent{Kind: "note", Body: text},
	}
}

func confluenceParseStaleBanner(rawXHTML string) ast.BlockContent {
	// Best-effort: extract any text content.
	return ast.BlockContent{
		StaleBanner: &ast.StaleBannerContent{},
	}
}

// stripTags removes all XML/HTML tags from a string.
var reAnyTag = regexp.MustCompile(`<[^>]+>`)

func stripTags(s string) string {
	return reAnyTag.ReplaceAllString(s, "")
}

// extractCDATA extracts the content of the first CDATA section in s.
func extractCDATA(s string) string {
	const open = "<![CDATA["
	const close = "]]>"
	start := strings.Index(s, open)
	if start < 0 {
		return stripTags(s)
	}
	start += len(open)
	end := strings.Index(s[start:], close)
	if end < 0 {
		return s[start:]
	}
	return s[start : start+end]
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared helpers
// ─────────────────────────────────────────────────────────────────────────────

// buildAnchorsForPage builds a StructuralAnchor for each block in blocks.
// It walks the blocks to compute the current heading path and same-kind ordinal
// at each level. This is the same anchoring used by the markdown writer.
func buildAnchorsForPage(blocks []ast.Block) []ast.StructuralAnchor {
	anchors := make([]ast.StructuralAnchor, len(blocks))
	headingPath := ""
	kindCounters := make(map[string]int) // headingPath+kind → count

	for i, blk := range blocks {
		key := headingPath + string(blk.Kind)
		ordinal := kindCounters[key]
		kindCounters[key]++
		anchors[i] = ast.StructuralAnchor{
			HeadingPath: headingPath,
			Kind:        blk.Kind,
			Ordinal:     ordinal,
		}
		if blk.Kind == ast.BlockKindHeading && blk.Content.Heading != nil {
			headingPath = blk.Content.Heading.Text
			// Reset kind counters for blocks under the new heading.
			kindCounters = make(map[string]int)
		}
	}
	return anchors
}

// Compile-time check: ConfluenceWriter satisfies no public interface currently
// because WritePage needs a context (unlike the sync SinkWriter interface).
// The confluence and notion writers have a richer WritePage(ctx, page) signature.
var _ ConfluenceClient = (*MemoryConfluenceClient)(nil)
