#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 SourceBridge Contributors
#
# init-hub-secrets.sh — generate strong random secrets for docker-compose.hub.yml
#
# Usage:
#   ./scripts/init-hub-secrets.sh           # write .env in current directory
#   ./scripts/init-hub-secrets.sh --force   # overwrite an existing .env
#
# The generated .env is chmod 0600 and must never be committed to git.

set -euo pipefail

FORCE=false
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    *)
      echo "Usage: $0 [--force]" >&2
      exit 1
      ;;
  esac
done

# Allow callers to redirect output path for testing.
: "${SECRETS_OUTPUT_FILE:=.env}"

if [[ -f "$SECRETS_OUTPUT_FILE" ]] && [[ "$FORCE" != "true" ]]; then
  echo ""
  echo "ERROR: $SECRETS_OUTPUT_FILE already exists."
  echo "       Pass --force to overwrite it, or delete it manually first."
  echo ""
  exit 1
fi

# Verify openssl is available.
if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl is required but not found in PATH." >&2
  echo "       Install OpenSSL (macOS: brew install openssl; Linux: apt/yum install openssl)." >&2
  exit 1
fi

SURREAL_PASS="$(openssl rand -hex 32)"
GRPC_SECRET="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 32)"

cat > "$SECRETS_OUTPUT_FILE" <<EOF
# SourceBridge hub secrets — generated by scripts/init-hub-secrets.sh
# NEVER commit this file to git.  It is listed in .gitignore.
#
# Regenerate at any time with: ./scripts/init-hub-secrets.sh --force
# (All active sessions will be invalidated when secrets change.)

SURREAL_PASS=${SURREAL_PASS}
SOURCEBRIDGE_GRPC_SECRET=${GRPC_SECRET}
SOURCEBRIDGE_JWT_SECRET=${JWT_SECRET}
EOF

chmod 0600 "$SECRETS_OUTPUT_FILE"

echo ""
echo "============================================================"
echo "  SourceBridge hub secrets written to: $SECRETS_OUTPUT_FILE"
echo "============================================================"
echo ""
echo "  SURREAL_PASS          (SurrealDB password)    — 64 hex chars"
echo "  SOURCEBRIDGE_GRPC_SECRET (gRPC shared secret) — 64 hex chars"
echo "  SOURCEBRIDGE_JWT_SECRET  (JWT signing key)    — 64 hex chars"
echo ""
echo "  File permissions: 0600 (owner read/write only)"
echo ""
echo "  Next steps:"
echo "    1. Keep .env out of git (already in .gitignore)"
echo "    2. Start SourceBridge:"
echo "         docker compose -f docker-compose.hub.yml up -d"
echo "    3. The API server will no longer emit security warnings."
echo ""
echo "  To rotate secrets later, run:"
echo "    ./scripts/init-hub-secrets.sh --force"
echo "  Note: rotating secrets invalidates all active user sessions."
echo ""
