apiVersion: apps/v1
kind: Deployment
metadata:
  name: sourcebridge-web
  namespace: sourcebridge
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
